'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {PetPreview3D,PetRoom3D} from './Pet3D'

type PetType='cocker'|'panda'|'shiba'|'capybara'
type Sick='healthy'|'cold'|'tummy'|'tired'
type Stage='baby'|'young'|'adult'
type PetSex='male'|'female'|'unspecified'
type World={couple_id:string;pet_type:PetType|null;pet_name:string|null;pet_sex:PetSex;coins:number;xp:number;level:number;mood:string;energy:number;hunger:number;thirst:number;hygiene:number;fun:number;affection:number;health:number;sickness_status:Sick;growth_stage:Stage;adopted_at:string;room_theme:string;personality?:Record<string,number>;last_care_by:string|null;last_care_action:string|null;last_care_at:string|null;updated_at:string}
type Inventory={id:string;item_key:string;quantity:number;equipped:boolean}
type Plot={id:string;seed_key:string;stage:number;water_count:number;last_watered_by:string|null;last_watered_at:string|null}
type Expedition={id:string;zone:'forest'|'beach'|'mountain';status:string;returns_at:string;reward:any}
type CareLog={id:string;user_id:string;action:string;health_after:number;sickness_after:Sick;created_at:string}

const PETS:{id:PetType;name:string;desc:string;trait:string}[]=[
 {id:'cocker',name:'Cocker',desc:'Cariñoso, curioso y muy expresivo.',trait:'Le encanta jugar y estar cerca.'},
 {id:'panda',name:'Panda',desc:'Tranquilo, tierno y amante de las siestas.',trait:'Se relaja con facilidad.'},
 {id:'shiba',name:'Shiba',desc:'Independiente, juguetón y aventurero.',trait:'Siempre quiere explorar.'},
 {id:'capybara',name:'Capibara',desc:'Relajada, sociable y completamente chill.',trait:'Convierte cualquier lugar en hogar.'}
]
const SHOP=[
 {id:'bed',emoji:'🛏️',name:'Cama nube',price:80},{id:'plant',emoji:'🪴',name:'Monstera',price:45},{id:'ball',emoji:'🎾',name:'Pelota',price:35},
 {id:'lamp',emoji:'💡',name:'Lámpara cálida',price:65},{id:'rug',emoji:'🧶',name:'Alfombra',price:55},{id:'frame',emoji:'🖼️',name:'Cuadro',price:50},
 {id:'sofa',emoji:'🛋️',name:'Sofá nube',price:110},{id:'telescope',emoji:'🔭',name:'Telescopio',price:140},{id:'fountain',emoji:'⛲',name:'Fuente',price:160}
]

const actionLabels=(sex:PetSex):Record<string,string>=>sex==='female'?{feed:'la alimentó',water:'le dio agua',play:'jugó con ella',pet:'la acarició',rest:'la dejó descansar',clean:'la bañó',care:'la cuidó'}:{feed:'lo alimentó',water:'le dio agua',play:'jugó con él',pet:'lo acarició',rest:'lo dejó descansar',clean:'lo bañó',care:'lo cuidó'}
const sicknessLabel=(sex:PetSex):Record<Sick,string>=>({healthy:'Saludable',cold:sex==='female'?'Resfriadita':'Resfriadito',tummy:'Barriguita sensible',tired:sex==='female'?'Agotada':'Agotado'})
const stageLabel=(sex:PetSex):Record<Stage,string>=>({baby:sex==='female'?'Cachorra':'Cachorro',young:'Joven',adult:sex==='female'?'Adulta':'Adulto'})
const personalityLabel=(sex:PetSex):Record<string,string>=>({playful:sex==='female'?'Juguetona':'Juguetón',calm:sex==='female'?'Tranquila':'Tranquilo',curious:sex==='female'?'Curiosa':'Curioso',affectionate:sex==='female'?'Cariñosa':'Cariñoso'})

export default function WorldHub({coupleId,userId,partnerName='Tu compañero/a'}:{coupleId:string;userId:string;partnerName?:string}){
 const s=useMemo(()=>createClient(),[])
 const [world,setWorld]=useState<World|null>(null);const [inventory,setInventory]=useState<Inventory[]>([]);const [garden,setGarden]=useState<Plot[]>([]);const [activeExpedition,setActiveExpedition]=useState<Expedition|null>(null);const [careLog,setCareLog]=useState<CareLog[]>([])
 const [pick,setPick]=useState<PetType>('cocker');const [name,setName]=useState('');const [petSex,setPetSex]=useState<'male'|'female'>('female');const [tab,setTab]=useState<'home'|'shop'|'garden'|'explore'>('home');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [editingProfile,setEditingProfile]=useState(false);const [profileName,setProfileName]=useState('');const [profileSex,setProfileSex]=useState<'male'|'female'>('female')
 useEffect(()=>{load(true);const timer=setInterval(()=>load(true),5*60*1000);const ch=s.channel(`world-${coupleId}`).on('postgres_changes',{event:'*',schema:'public',table:'pet_worlds',filter:`couple_id=eq.${coupleId}`},()=>load(false)).on('postgres_changes',{event:'*',schema:'public',table:'garden_plots',filter:`couple_id=eq.${coupleId}`},()=>load(false)).on('postgres_changes',{event:'*',schema:'public',table:'expeditions',filter:`couple_id=eq.${coupleId}`},()=>load(false)).on('postgres_changes',{event:'INSERT',schema:'public',table:'pet_care_log',filter:`couple_id=eq.${coupleId}`},()=>load(false)).subscribe();return()=>{clearInterval(timer);s.removeChannel(ch)}},[coupleId])
 async function load(refresh=false){if(refresh)await s.rpc('pet_refresh_state');const [{data:w},{data:i},{data:g},{data:e},{data:l}]=await Promise.all([s.from('pet_worlds').select('*').eq('couple_id',coupleId).maybeSingle(),s.from('world_inventory').select('*').eq('couple_id',coupleId),s.from('garden_plots').select('*').eq('couple_id',coupleId).order('planted_at'),s.from('expeditions').select('*').eq('couple_id',coupleId).eq('status','active').maybeSingle(),s.from('pet_care_log').select('*').eq('couple_id',coupleId).order('created_at',{ascending:false}).limit(6)]);setWorld(w as World|null);setInventory((i||[]) as Inventory[]);setGarden((g||[]) as Plot[]);setActiveExpedition(e as Expedition|null);setCareLog((l||[]) as CareLog[])}
 async function rpc<T>(fn:string,args:any={}){setBusy(true);setMsg('');const {data,error}=await s.rpc(fn,args);setBusy(false);if(error){const code=(error.message||'').toUpperCase();const friendly=code.includes('NOT_ENOUGH_COINS')?'Faltan monedas. Jueguen unas rondas y vuelvan.':code.includes('TOO_FAST')?'Dale un segundo 😄':code.includes('TOO_TIRED')?'Está demasiado cansado para jugar. Déjalo descansar.':code.includes('PET_NEEDS_RECOVERY')?'Primero necesita recuperarse antes de salir de expedición.':code.includes('NOT_SICK')?'Está saludable; no necesita cuidados especiales.':code.includes('NOT_READY')?'Todavía está explorando.':code.includes('GARDEN_FULL')?'El jardín está lleno.':code.includes('WAIT_BEFORE_WATERING')?'Esa planta acaba de recibir agua.':code.includes('INVALID_PET_SEX')?'Elige Macho o Hembra.':`No pudimos completar la acción: ${error.message}`;setMsg(friendly);return null}await load(false);return data as T}
 async function adopt(){if(!name.trim())return setMsg('Pónganle un nombre primero.');await rpc('adopt_pet',{p_type:pick,p_name:name.trim(),p_sex:petSex})}
 async function saveProfile(){if(!profileName.trim())return setMsg('El nombre no puede quedar vacío.');const result=await rpc<World>('update_pet_profile',{p_name:profileName.trim(),p_sex:profileSex});if(result){setEditingProfile(false);setMsg('Perfil de la mascota actualizado ✨')}}
 async function act(kind:'feed'|'water'|'play'|'pet'|'rest'|'clean'|'care'){await rpc('pet_interact',{p_action:kind})}
 async function buy(item:(typeof SHOP)[number]){await rpc('buy_world_item',{p_item_key:item.id})}
 async function plant(){await rpc('plant_garden',{p_seed:'sunflower'})}
 async function waterGarden(id:string){await rpc('water_garden',{p_plot_id:id})}
 async function expedition(zone:'forest'|'beach'|'mountain'){await rpc('start_expedition',{p_zone:zone})}
 async function claim(){if(!activeExpedition)return;const result=await rpc<World>('claim_expedition',{p_expedition_id:activeExpedition.id});if(result)setMsg(`¡${world?.pet_name||'La mascota'} volvió! Recompensa añadida al mundo ✨`)}
 if(!world?.pet_type)return <div className="world-shell"><div className="world-intro"><div className="eyebrow">Nuestro mundo</div><h1>Elijan a quien vivirá con ustedes</h1><p>Una mascota 3D compartida con necesidades y crecimiento persistentes. Puede sentirse mal si descuidan sus necesidades, pero nunca muere ni pierde todo su progreso.</p></div><div className="pet-picker">{PETS.map(p=><button key={p.id} className={pick===p.id?'selected':''} onClick={()=>setPick(p.id)}><div className="pet-preview-stage"><PetPreview3D type={p.id}/></div><h3>{p.name}</h3><p>{p.desc}</p><small>{p.trait}</small></button>)}</div><div className="adopt-box"><label>¿Cómo se llamará?<input value={name} maxLength={24} onChange={e=>setName(e.target.value)} placeholder="Nombre"/></label><div className="pet-sex-field"><span>¿Es macho o hembra?</span><div className="segmented pet-sex-selector"><button type="button" className={petSex==='male'?'active':''} onClick={()=>setPetSex('male')}>♂️ Macho</button><button type="button" className={petSex==='female'?'active':''} onClick={()=>setPetSex('female')}>♀️ Hembra</button></div><small>Esto personaliza su ficha y los textos. No cambia estadísticas ni ventajas.</small></div><button className="btn" disabled={busy} onClick={adopt}>{busy?'Creando mundo…':'Adoptar y crear nuestro mundo'}</button>{msg&&<p className="tiny">{msg}</p>}</div></div>
 const owned=new Set(inventory.map(x=>x.item_key));const xpFloor=(world.level-1)*120;const personality=world.personality||{};const trait=Object.entries(personality).sort((a,b)=>Number(b[1])-Number(a[1]))[0]?.[0]||'affectionate';const traitLabel=personalityLabel(world.pet_sex);const xpPct=Math.max(0,Math.min(100,((world.xp-xpFloor)/120)*100));const ready=activeExpedition&&new Date(activeExpedition.returns_at).getTime()<=Date.now();const visualMood=world.sickness_status!=='healthy'?'sick':world.energy<25?'sleepy':world.hygiene<28?'dirty':world.fun<28?'bored':world.affection<30?'lonely':world.mood
 return <div className="world-shell"><div className="world-top"><div><div className="eyebrow">Nuestro mundo · nivel {world.level}</div><h1>{world.pet_name}</h1><div className="pet-meta-line"><span>{stageLabel(world.pet_sex)[world.growth_stage]}</span><span>{world.pet_sex==='female'?'♀️ Hembra':world.pet_sex==='male'?'♂️ Macho':'⚪ Sin definir'}</span><span>Personalidad: <b>{traitLabel[trait]||'Cariñoso'}</b></span><span className={world.sickness_status==='healthy'?'healthy':'unwell'}>{world.sickness_status==='healthy'?'❤️ Saludable':`🩹 ${sicknessLabel(world.pet_sex)[world.sickness_status]}`}</span><button className="pet-profile-edit" onClick={()=>{setProfileName(world.pet_name||'');setProfileSex(world.pet_sex==='male'?'male':'female');setEditingProfile(true)}}>Editar perfil</button></div>{editingProfile&&<div className="pet-profile-editor"><label>Nombre<input value={profileName} maxLength={24} onChange={e=>setProfileName(e.target.value)}/></label><div><span>Sexo</span><div className="segmented pet-sex-selector"><button type="button" className={profileSex==='male'?'active':''} onClick={()=>setProfileSex('male')}>♂️ Macho</button><button type="button" className={profileSex==='female'?'active':''} onClick={()=>setProfileSex('female')}>♀️ Hembra</button></div></div><div className="pet-profile-actions"><button className="round-back" onClick={()=>setEditingProfile(false)}>Cancelar</button><button className="btn" disabled={busy} onClick={saveProfile}>{busy?'Guardando…':'Guardar'}</button></div></div>}<div className="level-line"><i style={{width:`${xpPct}%`}}/></div></div><div className="world-currency"><b>🪙 {world.coins}</b><span>✨ {world.xp} XP</span></div></div>
 <div className="world-tabs"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>Hogar</button><button className={tab==='shop'?'active':''} onClick={()=>setTab('shop')}>Decorar</button><button className={tab==='garden'?'active':''} onClick={()=>setTab('garden')}>Jardín</button><button className={tab==='explore'?'active':''} onClick={()=>setTab('explore')}>Explorar</button></div>
 {tab==='home'&&<><div className={`pet-room pet-room-v4 pet-room-v5 theme-${world.room_theme||'warm'}`}><div className="pet-room-3d-layer"><PetRoom3D type={world.pet_type} mood={visualMood} items={inventory.filter(x=>x.equipped).map(x=>x.item_key)} growthStage={world.growth_stage}/></div><div className="pet-center pet-center-overlay"><div className="pet-speech">{speech(world)}</div></div><div className="pet-stats pet-stats-v5"><Stat label="Salud" value={world.health}/><Stat label="Comida" value={world.hunger}/><Stat label="Agua" value={world.thirst}/><Stat label="Energía" value={world.energy}/><Stat label="Higiene" value={world.hygiene}/><Stat label="Diversión" value={world.fun}/><Stat label="Afecto" value={world.affection}/></div><div className="pet-actions pet-actions-v5"><button disabled={busy} onClick={()=>act('feed')}>🥣<b>Comer</b></button><button disabled={busy} onClick={()=>act('water')}>💧<b>Agua</b></button><button disabled={busy||world.energy<12} onClick={()=>act('play')}>🎾<b>Jugar</b></button><button disabled={busy} onClick={()=>act('pet')}>🤍<b>Acariciar</b></button><button disabled={busy} onClick={()=>act('rest')}>🌙<b>Dormir</b></button><button disabled={busy} onClick={()=>act('clean')}>🫧<b>Bañar</b></button>{world.sickness_status!=='healthy'&&<button className="care-special" disabled={busy||world.coins<10} onClick={()=>act('care')}>🧰<b>Cuidados</b><small>10 🪙</small></button>}</div></div><section className="pet-life-card"><div><h2>Vida diaria</h2><p>Las necesidades cambian con el tiempo aunque la app esté cerrada. Nunca bajan a un punto de muerte: la salud tiene un piso de seguridad.</p></div><div className="pet-care-history"><b>Cuidados recientes</b>{careLog.length?careLog.slice(0,4).map(x=><span key={x.id}>{x.user_id===userId?'Tú':partnerName} {actionLabels(world.pet_sex)[x.action]||'cuidó a la mascota'} · {relativeTime(x.created_at)}</span>):<span>Aún no hay cuidados registrados.</span>}</div></section></>}
 {tab==='shop'&&<div><div className="section-title"><div><h2>Hagan suyo el espacio</h2><p className="muted">Las monedas se ganan jugando; no existe compra con dinero real.</p></div><span>{owned.size}/{SHOP.length} objetos</span></div><div className="shop-grid">{SHOP.map(it=><button key={it.id} disabled={busy||owned.has(it.id)||world.coins<it.price} onClick={()=>buy(it)}><span>{it.emoji}</span><h3>{it.name}</h3><p>{owned.has(it.id)?'✓ Ya lo tienen':world.coins<it.price?`Faltan ${it.price-world.coins} 🪙`:`🪙 ${it.price}`}</p></button>)}</div></div>}
 {tab==='garden'&&<div><section className="garden-card"><div><h2>🌱 Jardín compartido</h2><p>La misma planta puede crecer con acciones de ambos. El progreso queda guardado en Supabase.</p></div><button className="btn secondary" disabled={busy||world.coins<20||garden.length>=12} onClick={plant}>Plantar · 20 🪙</button></section><div className="garden-grid">{garden.map(g=><button key={g.id} disabled={busy||g.stage>=3} onClick={()=>waterGarden(g.id)}><span>{['🌱','🌿','🌷','🌻'][g.stage]}</span><small>{g.stage<3?`Etapa ${g.stage+1}/4 · regar`:'Floreció ✨'}</small>{g.last_watered_by&&<em>{g.last_watered_by===userId?'Regaste tú':`Regó ${partnerName}`}</em>}</button>)}{garden.length===0&&<div className="empty-mini">Todavía no plantaron nada. La primera semilla cuesta 20 monedas.</div>}</div></div>}
 {tab==='explore'&&<div>{activeExpedition?<section className="expedition-active"><div className="expedition-scene"><span>🏡</span><i>· · · · ·</i><span>{activeExpedition.zone==='forest'?'🌲':activeExpedition.zone==='beach'?'🏖️':'🏔️'}</span></div><h2>{world.pet_name} está explorando</h2><p>{zoneName(activeExpedition.zone)} · regreso {new Date(activeExpedition.returns_at).toLocaleString('es-PE',{dateStyle:'short',timeStyle:'short'})}</p><button className="btn" disabled={busy||!ready} onClick={claim}>{ready?'Recibir a '+world.pet_name:'Todavía explorando…'}</button>{ready&&<p className="tiny">La recompensa se calcula en el servidor y solo puede reclamarse una vez.</p>}</section>:<><div className="section-title"><div><h2>Elijan una expedición</h2><p className="muted">Continúa mientras la app está cerrada.</p></div></div><div className="expedition-grid"><button disabled={busy||world.health<45||world.energy<25} onClick={()=>expedition('forest')}>🌲<h3>Bosque</h3><p>{world.health<45||world.energy<25?'Primero necesita recuperarse':'4 horas'}</p><small>55 🪙 · 20 XP</small></button><button disabled={busy||world.level<2||world.health<45||world.energy<25} onClick={()=>expedition('beach')}>🏖️<h3>Playa</h3><p>{world.level<2?'Se desbloquea en nivel 2':world.health<45||world.energy<25?'Primero necesita recuperarse':'6 horas'}</p><small>75 🪙 · 25 XP</small></button><button disabled={busy||world.level<3||world.health<45||world.energy<25} onClick={()=>expedition('mountain')}>🏔️<h3>Montaña</h3><p>{world.level<3?'Se desbloquea en nivel 3':world.health<45||world.energy<25?'Primero necesita recuperarse':'8 horas'}</p><small>105 🪙 · 35 XP</small></button></div></>}</div>}
 {msg&&<div className="notice">{msg}</div>}</div>
}
function Stat({label,value}:{label:string;value:number}){return <div><span>{label}<b>{value}%</b></span><div><i style={{width:`${value}%`}}/></div></div>}
function zoneName(z:string){return z==='forest'?'Bosque':z==='beach'?'Playa':'Montaña'}
function speech(w:World){const f=w.pet_sex==='female';if(w.sickness_status==='cold')return `No me siento al 100%… quiero descansar y estar ${f?'acompañada':'acompañado'} 🥺`;if(w.sickness_status==='tummy')return 'Mi barriguita está sensible. Un poco de cuidado me vendría bien.';if(w.sickness_status==='tired')return `Estoy ${f?'agotada':'agotado'}… necesito agua, descanso y cariño.`;if(w.energy<25)return 'Tengo mucho sueño… ¿descansamos?';if(w.thirst<30)return 'Tengo sed 💧';if(w.hunger<30)return '¿Comemos algo?';if(w.hygiene<28)return 'Creo que necesito un baño 🫧';if(w.fun<28)return `Estoy ${f?'aburrida':'aburrido'}… ¿jugamos?`;if(w.affection<30)return '¿Un poquito de cariño? 🤍';return w.mood==='calm'?'Qué tranquilo está todo ✨':'¿Qué hacemos hoy?'}
function relativeTime(date:string){const mins=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/60000));if(mins<1)return 'ahora';if(mins<60)return `hace ${mins} min`;const h=Math.floor(mins/60);if(h<24)return `hace ${h} h`;return `hace ${Math.floor(h/24)} d`}
