'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {useRouter} from 'next/navigation'
import GamesHub from './games/GamesHub'
import WorldHub from './world/WorldHub'
import WeeklyChallenge from './WeeklyChallenge'
import Achievements from './Achievements'

const seed=[['Cómo estoy','¿Cómo te sientes hoy, sin pensar en lo que “deberías” sentir?'],['Lo que necesito','¿Qué necesitas más esta semana: calma, compañía, espacio o diversión?'],['Lo que valoro','¿Qué cosa pequeña agradeces hoy?'],['Cambios','¿Qué te gustaría hacer distinto estos días?'],['Construir','¿Qué te gustaría que cuidemos juntos esta semana?']]
type Tab='inicio'|'miespacio'|'jugar'|'nosotros'|'mundo'|'ajustes'
type Reflection={id:string;user_id:string;chapter:string;prompt:string;body:string;visibility:'private'|'shared';created_at:string}
type Agreement={id:string;title:string;detail:string|null;status:string}
type Activity={id:string;title:string;activity_date:string|null}
type Member={user_id:string;display_name:string|null}

export default function Dashboard(){const s=useMemo(()=>createClient(),[]);const router=useRouter();const [tab,setTab]=useState<Tab>('inicio');const [userId,setUserId]=useState('');const [coupleId,setCoupleId]=useState('');const [partnerName,setPartnerName]=useState('Tu compañero/a');const [invite,setInvite]=useState('');const [idx,setIdx]=useState(0);const [text,setText]=useState('');const [mine,setMine]=useState<Reflection[]>([]);const [shared,setShared]=useState<Reflection[]>([]);const [agreements,setAgreements]=useState<Agreement[]>([]);const [activities,setActivities]=useState<Activity[]>([]);const [title,setTitle]=useState('');const [date,setDate]=useState('');const [agreement,setAgreement]=useState('');const [detail,setDetail]=useState('');const [status,setStatus]=useState('');const [pointsPulse,setPointsPulse]=useState(0)
 useEffect(()=>{boot()},[])
 async function boot(){const {data:{user}}=await s.auth.getUser();if(!user)return;setUserId(user.id);const {data:m}=await s.from('memberships').select('couple_id').eq('user_id',user.id).maybeSingle();if(!m?.couple_id)return;setCoupleId(m.couple_id);const [{data:members},{data:couple}]=await Promise.all([s.from('memberships').select('user_id,display_name').eq('couple_id',m.couple_id),s.from('couples').select('invite_code').eq('id',m.couple_id).maybeSingle()]);const other=(members as Member[]|null)?.find(x=>x.user_id!==user.id);if(other?.display_name)setPartnerName(other.display_name);setInvite(couple?.invite_code||'');refresh(user.id,m.couple_id)}
 async function refresh(uid=userId,cid=coupleId){if(!uid||!cid)return;const [{data:a},{data:r},{data:ag},{data:act}]=await Promise.all([s.from('reflections').select('*').eq('user_id',uid).order('created_at',{ascending:false}),s.from('reflections').select('*').eq('couple_id',cid).eq('visibility','shared').neq('user_id',uid).order('created_at',{ascending:false}),s.from('agreements').select('*').eq('couple_id',cid).order('created_at',{ascending:false}),s.from('activities').select('*').eq('couple_id',cid).order('activity_date',{ascending:true})]);setMine((a||[]) as Reflection[]);setShared((r||[]) as Reflection[]);setAgreements((ag||[]) as Agreement[]);setActivities((act||[]) as Activity[])}
 async function saveAnswer(){if(!text.trim())return setStatus('Escribe algo antes de guardar.');const q=seed[idx];const {error}=await s.from('reflections').insert({user_id:userId,couple_id:coupleId,chapter:q[0],prompt:q[1],body:text.trim(),visibility:'private'});setStatus(error?'No pudimos guardar.':'Guardado solo para ti 🤍');if(!error){setText('');refresh()}}
 async function toggleShare(r:Reflection){const visibility=r.visibility==='private'?'shared':'private';await s.from('reflections').update({visibility,updated_at:new Date().toISOString()}).eq('id',r.id);setStatus(visibility==='shared'?`Compartido. ${partnerName} podrá verlo.`:'Volvió a ser privado.');refresh()}
 async function addPlan(){if(!title.trim())return;const {error}=await s.from('activities').insert({couple_id:coupleId,created_by:userId,title:title.trim(),activity_date:date||null});if(!error){setTitle('');setDate('');refresh()}}
 async function addAgreement(){if(!agreement.trim())return;const {error}=await s.from('agreements').insert({couple_id:coupleId,created_by:userId,title:agreement.trim(),detail:detail.trim()||null});if(!error){setAgreement('');setDetail('');refresh()}}
 async function leaveSpace(){if(!confirm('¿Salir de este espacio? Si fue creado por error podrás unirte al correcto después. El contenido compartido no se borra automáticamente.'))return;const {error}=await s.rpc('leave_couple_space');if(error)return setStatus('No pudimos salir del espacio.');router.replace('/onboarding');router.refresh()}
 async function logout(){await s.auth.signOut();router.push('/')}
 const todayGame=['🧠 Mentes conectadas','🎨 Dibuja y adivina','🗺️ La aventura'][new Date().getDate()%3]
 return <main className="shell native-app-shell"><header className="topbar new"><button className="brand-button" onClick={()=>setTab('inicio')}><span className="brand-mark">🐼</span><span>Pandalandia</span></button><div className="desktop-nav">{([['inicio','⌂','Inicio'],['miespacio','◌','Mi espacio'],['jugar','🎮','Jugar'],['nosotros','♡','Juntos'],['mundo','🐾','Mundo']] as [Tab,string,string][]).map(([k,ic,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><span className="nav-ic">{ic}</span><span className="nav-label">{n}</span>{k==='jugar'&&<i/>}</button>)}</div><button className="avatar-btn" aria-label="Abrir configuración" onClick={()=>setTab('ajustes')}>⚙</button></header>
 <div className="app-wrap"><div className="mobile-appbar"><button className="mobile-brand" onClick={()=>setTab('inicio')}><span>🐼</span><strong>Pandalandia</strong></button><button className="mobile-settings" aria-label="Configuración" onClick={()=>setTab('ajustes')}>⚙</button></div>{tab==='inicio'&&<Home partnerName={partnerName} todayGame={todayGame} onPlay={()=>setTab('jugar')} onWorld={()=>setTab('mundo')} onReflect={()=>setTab('miespacio')} pointsPulse={pointsPulse}/>} 
 {tab==='miespacio'&&<section className="content-page"><div className="page-head"><div><div className="eyebrow">Solo para ti</div><h1>Mi espacio</h1><p>Primero entiendes lo tuyo. Compartir siempre es una decisión.</p></div></div><div className="reflection-layout"><aside className="chapter-list">{seed.map((q,i)=><button className={i===idx?'active':''} onClick={()=>setIdx(i)} key={q[0]}><span>0{i+1}</span>{q[0]}</button>)}</aside><div className="reflection-main"><div className="reflection-card"><span className="privacy-chip">🔒 Solo yo</span><h2>{seed[idx][1]}</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Escribe sin intentar sonar perfecto…"/><div className="actions"><button className="btn" onClick={saveAnswer}>Guardar privado</button><button className="btn ghost" onClick={()=>setIdx((idx+1)%seed.length)}>Otra pregunta</button></div>{status&&<p className="tiny">{status}</p>}</div><div className="journal-list">{mine.map(r=><article key={r.id}><div><span>{r.visibility==='private'?'🔒 Privado':'💌 Compartido'}</span><small>{new Date(r.created_at).toLocaleDateString()}</small></div><h3>{r.chapter}</h3><p className="prompt-small">{r.prompt}</p><p>{r.body}</p><button onClick={()=>toggleShare(r)}>{r.visibility==='private'?'Compartir con ambos':'Hacer privado'}</button></article>)}</div></div></div></section>}
 {tab==='jugar'&&coupleId&&<GamesHub coupleId={coupleId} userId={userId} partnerName={partnerName} onPoints={n=>{setPointsPulse(n);setTimeout(()=>setPointsPulse(0),1800)}}/>}
 {tab==='nosotros'&&<section className="content-page"><div className="page-head"><div><div className="eyebrow">Lo que construyen</div><h1>Juntos</h1><p>Lo compartido, los acuerdos y planes viven aquí. Nada privado aparece sin permiso.</p></div></div><div className="shared-columns"><div><h2>💌 Compartido contigo</h2>{shared.length?shared.map(r=><article className="soft-card" key={r.id}><span>{r.chapter}</span><h3>{r.prompt}</h3><p>{r.body}</p></article>):<div className="empty-mini">Cuando {partnerName} comparta una reflexión, aparecerá aquí.</div>}</div><div><h2>🤝 Acuerdos</h2><div className="compose"><input value={agreement} onChange={e=>setAgreement(e.target.value)} placeholder="Un acuerdo sencillo…"/><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="¿Cómo lo harán?"/><button className="btn" onClick={addAgreement}>Guardar acuerdo</button></div>{agreements.map(a=><article className="agreement-row" key={a.id}><span>✓</span><div><b>{a.title}</b>{a.detail&&<p>{a.detail}</p>}</div></article>)}</div><div><h2>🌿 Planes</h2><div className="compose"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Algo que quieren hacer…"/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn secondary" onClick={addPlan}>Añadir plan</button></div>{activities.map(a=><article className="agreement-row" key={a.id}><span>○</span><div><b>{a.title}</b>{a.activity_date&&<p>{new Date(a.activity_date+'T12:00:00').toLocaleDateString()}</p>}</div></article>)}</div></div>{coupleId&&<WeeklyChallenge coupleId={coupleId} userId={userId} partnerName={partnerName}/>} {coupleId&&<Achievements coupleId={coupleId} userId={userId}/>}</section>}
 {tab==='mundo'&&coupleId&&<WorldHub coupleId={coupleId} userId={userId} partnerName={partnerName}/>} 
 {tab==='ajustes'&&<section className="settings-page"><div className="eyebrow">Configuración</div><h1>Su espacio</h1><div className="settings-card"><h3>Código de invitación</h3><p className="muted">Solo hace falta mientras falta vincular a la segunda persona.</p><div className="inviteCode">{invite||'—'}</div></div><div className="settings-card danger"><h3>¿Creaste el espacio equivocado?</h3><p>Puedes salir y volver al onboarding para ingresar el código correcto. No eliminamos automáticamente contenido compartido.</p><button className="btn ghost" onClick={leaveSpace}>Salir de este espacio</button></div><button className="btn" onClick={logout}>Cerrar sesión</button>{status&&<p>{status}</p>}</section>}
 </div><nav className="mobile-nav">{([['inicio','⌂','Inicio'],['miespacio','◌','Mi espacio'],['jugar','🎮','Jugar'],['nosotros','♡','Juntos'],['mundo','🐾','Mundo']] as [Tab,string,string][]).map(([k,ic,n])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}><span>{ic}</span>{n}</button>)}</nav>{pointsPulse>0&&<div className="points-toast">+{pointsPulse} pts ✨</div>}</main>}
function Home({partnerName,todayGame,onPlay,onWorld,onReflect,pointsPulse}:{partnerName:string;todayGame:string;onPlay:()=>void;onWorld:()=>void;onReflect:()=>void;pointsPulse:number}){return <div className="home-v40">
<section className="v40-welcome"><div className="v40-welcome-copy"><span className="v40-overline">SU ESPACIO · SOLO USTEDES</span><h1>Un pequeño mundo<br/><em>hecho de dos.</em></h1><p>Jueguen, cuiden a Mia y sigan construyendo momentos incluso cuando no estén conectados al mismo tiempo.</p><div className="v40-welcome-actions"><button className="v40-primary" onClick={onPlay}>Jugar ahora →</button><button className="v40-secondary" onClick={onWorld}>🐾 Ver a Mia</button></div></div><div className="v40-hero-art"><div className="v40-moon"/><div className="v40-island"><span>🐼</span><i>♥</i><span>🐼</span></div></div></section>
<section className="v40-dock"><button onClick={onPlay}><i className="play">▶</i><span><b>Jugar</b><small>25 juegos juntos</small></span></button><button onClick={onWorld}><i className="pet">🐾</i><span><b>Mia</b><small>Tu cachorra está en casa</small></span></button><button onClick={onReflect}><i className="note">✎</i><span><b>Mi espacio</b><small>Escribe algo para ti</small></span></button></section>
<section className="v40-grid"><button className="v40-feature" onClick={onPlay}><small>RECOMENDADO PARA HOY · 03 MIN</small><div><span>JUEGO DE PAREJA</span><h2>{todayGame}</h2><p>Una partida corta para descubrir algo nuevo del otro.</p></div><b>Empezar ↗</b></button><button className="v40-pet" onClick={onWorld}><header><span>● MIA · EN CASA</span><em>NIVEL 8</em></header><div className="v40-pet-face">🐶</div><footer><span><b>Todo bien</b><small>Feliz · con energía</small></span><i>→</i></footer></button><div className="v40-streak"><strong>7</strong><span><small>DÍAS ESTA SEMANA</small><b>Van muy bien juntos.</b><p>Continúen sumando momentos.</p></span><i>✦</i></div></section>
</div>}
