'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type Challenge={id:string;type:'versus'|'coop';prize:string|null;goal:number;status:string;accepted_by:string[];week_start:string;winner_id:string|null;completed_at:string|null;reward_claimed:boolean}
export default function WeeklyChallenge({coupleId,userId,partnerName='Tu persona'}:{coupleId:string;userId:string;partnerName?:string}){
 const s=useMemo(()=>createClient(),[]);const [challenge,setChallenge]=useState<Challenge|null>(null);const [scores,setScores]=useState<Record<string,number>>({});const [type,setType]=useState<'versus'|'coop'>('versus');const [prize,setPrize]=useState('Quien gane elige la próxima película');const [goal,setGoal]=useState(500);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{load();const ch=s.channel(`weekly-${coupleId}`).on('postgres_changes',{event:'*',schema:'public',table:'weekly_challenges',filter:`couple_id=eq.${coupleId}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_scores',filter:`couple_id=eq.${coupleId}`},load).subscribe();return()=>{s.removeChannel(ch)}},[coupleId])
 function monday(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
 async function load(){await s.rpc('settle_previous_weekly_challenges');const m=monday(),key=m.toISOString().slice(0,10);const [{data},{data:sc}]=await Promise.all([s.from('weekly_challenges').select('*').eq('couple_id',coupleId).eq('week_start',key).maybeSingle(),s.from('game_scores').select('user_id,points').eq('couple_id',coupleId).gte('created_at',m.toISOString())]);setChallenge(data as Challenge|null);const map:Record<string,number>={};(sc||[]).forEach((x:any)=>map[x.user_id]=(map[x.user_id]||0)+x.points);setScores(map)}
 async function create(){setBusy(true);setMsg('');const {data,error}=await s.rpc('propose_weekly_challenge',{p_type:type,p_prize:type==='versus'?prize:null,p_goal:goal});setBusy(false);if(error)setMsg(error.message);else setChallenge(data as Challenge)}
 async function claimReward(){if(!challenge)return;setBusy(true);const {error}=await s.rpc('claim_weekly_reward',{p_challenge_id:challenge.id});setBusy(false);if(error)setMsg(error.message);else{setMsg('Recompensa añadida a Nuestro mundo ✨');load()}}
 async function accept(){if(!challenge)return;setBusy(true);const {data,error}=await s.rpc('accept_weekly_challenge',{p_challenge_id:challenge.id});setBusy(false);if(error)setMsg(error.message);else setChallenge(data as Challenge)}
 if(!challenge)return <div className="challenge-create"><div><div className="eyebrow">Reto semanal</div><h2>Una semana, un trato</h2><p className="muted">Compitan o jueguen contra una meta conjunta. Los puntos semanales empiezan de cero cada lunes; su mundo no.</p></div><div className="challenge-form"><div className="segmented"><button className={type==='versus'?'active':''} onClick={()=>setType('versus')}>⚔️ Tú vs yo</button><button className={type==='coop'?'active':''} onClick={()=>setType('coop')}>🤝 Nosotros vs juego</button></div>{type==='versus'?<label>Premio acordado<input maxLength={180} value={prize} onChange={e=>setPrize(e.target.value)} placeholder="Ej. quien gane elige la película"/></label>:<label>Meta conjunta<input type="number" min={100} max={100000} step={50} value={goal} onChange={e=>setGoal(Number(e.target.value))}/></label>}<button className="btn" disabled={busy||type==='versus'&&!prize.trim()} onClick={create}>{busy?'Guardando…':'Proponer reto'}</button>{msg&&<p className="tiny">{msg}</p>}</div></div>
 const mine=scores[userId]||0;const others=Object.entries(scores).filter(([k])=>k!==userId).reduce((a,[,v])=>a+v,0);const accepted=challenge.accepted_by?.includes(userId);const active=challenge.status==='active';const total=mine+others;const pct=Math.min(100,total/challenge.goal*100)
 return <div className="challenge-card"><div className="challenge-head"><div><div className="eyebrow">Reto de esta semana</div><h2>{challenge.type==='versus'?'Tú vs '+partnerName:'Ustedes vs el juego'}</h2></div><span className={active?'status-live':'status-wait'}>{active?'● EN JUEGO':'ESPERANDO ACUERDO'}</span></div>{challenge.type==='versus'?<><div className="scoreboard"><div><span>Tú</span><b>{mine}</b></div><em>VS</em><div><span>{partnerName}</span><b>{others}</b></div></div><div className="prize-box">🏆 <div><small>Premio acordado</small><b>{challenge.prize}</b></div></div></>:<><div className="coop-progress"><div><i style={{width:`${pct}%`}}/></div><b>{total} / {challenge.goal} pts</b></div><div className="prize-box">🎁 <div><small>Meta cooperativa</small><b>{pct>=100?'¡Meta alcanzada! ✨':'Sigan jugando para completar la semana'}</b></div></div>{pct>=100&&!challenge.reward_claimed&&<button className="btn secondary" disabled={busy} onClick={claimReward}>Desbloquear recompensa</button>}{challenge.reward_claimed&&<p className="muted">🏆 Recompensa semanal ya enviada a Nuestro mundo.</p>}</>}{!accepted&&<button className="btn" disabled={busy} onClick={accept}>Acepto el reto</button>}{accepted&&!active&&<p className="muted">Tú aceptaste. Falta que {partnerName} acepte el mismo premio o meta.</p>}<p className="tiny">Los puntos vienen de partidas finalizadas y los calcula el servidor; el cliente no decide cuántos otorgar.</p>{msg&&<p className="tiny">{msg}</p>}</div>
}
