import fs from 'node:fs'
const p='components/world/Pet3D.tsx'
let s=fs.readFileSync(p,'utf8')
const rep=(a,b,n)=>{if(!s.includes(a))throw new Error(`V70 target missing: ${n}`);s=s.replace(a,b)}
rep("function PremiumCocker({mood='happy',behavior='idle',behaviorNonce=0,onInteract}:{mood?:Mood;behavior?:PetBehavior;behaviorNonce?:number;onInteract?:()=>void}){","function PremiumCocker({mood='happy',behavior='idle',behaviorNonce=0,items=[],onInteract}:{mood?:Mood;behavior?:PetBehavior;behaviorNonce?:number;items?:string[];onInteract?:()=>void}){",'cocker items')
rep("   <Nose position={[0,-.02,.72]} scale={.90}/><Mouth mood={mood} z={.73}/><Blush x={-.34} z={.58}/><Blush x={.34} z={.58}/>\n  </group>","   <Nose position={[0,-.02,.72]} scale={.90}/><Mouth mood={mood} z={.73}/><Blush x={-.34} z={.58}/><Blush x={.34} z={.58}/>\n   <Wearables items={items} behavior={behavior} mount=\"head\"/>\n  </group>",'head mount')
rep("function Wearables({items=[],behavior='idle'}:{items?:string[];behavior?:PetBehavior}){\n const has=(k:string)=>items.includes(k)","const HEAD_WEARABLE_IDS=new Set(['bow_red','cap','flower_crown','gold_crown','diamond_crown','round_glasses','heart_glasses'])\nfunction Wearables({items=[],behavior='idle',mount='body'}:{items?:string[];behavior?:PetBehavior;mount?:'head'|'body'}){\n const mountedItems=items.filter(id=>mount==='head'?HEAD_WEARABLE_IDS.has(id):!HEAD_WEARABLE_IDS.has(id))\n const has=(k:string)=>mountedItems.includes(k)",'registry')
for(const [a,b] of [["position={[0,1.01,.18]}","position={[0,.34,-.20]}"],["position={[0,1.05,.08]}","position={[0,.40,-.31]}"],["position={[0,1.07,.10]}","position={[0,.41,-.29]}"],["position={[0,1.15,.09]}","position={[0,.54,-.32]}"],["position={[0,1.17,.09]}","position={[0,.56,-.32]}"],["position={[0,.62,.65]}","position={[0,.12,.23]}"],["position={[0,.62,.67]}","position={[0,.12,.25]}"]]){if(s.includes(a))s=s.replace(a,b)}
rep("function ProceduralPet({type,mood,behavior='idle',behaviorNonce=0,onInteract}:{type:PetType;mood:Mood;behavior?:PetBehavior;behaviorNonce?:number;onInteract?:()=>void}){","function ProceduralPet({type,mood,behavior='idle',behaviorNonce=0,items=[],onInteract}:{type:PetType;mood:Mood;behavior?:PetBehavior;behaviorNonce?:number;items?:string[];onInteract?:()=>void}){",'procedural items')
s=s.replace("<PremiumCocker mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} onInteract={onInteract}/>","<PremiumCocker mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} items={items} onInteract={onInteract}/>")
rep("function HighFidelityPet({type,mood,behavior='idle',behaviorNonce=0,onInteract}:{type:PetType;mood:Mood;behavior?:PetBehavior;behaviorNonce?:number;onInteract?:()=>void}){","function HighFidelityPet({type,mood,behavior='idle',behaviorNonce=0,items=[],onInteract}:{type:PetType;mood:Mood;behavior?:PetBehavior;behaviorNonce?:number;items?:string[];onInteract?:()=>void}){",'hf items')
s=s.replace("<PremiumCocker mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} onInteract={onInteract}/>","<PremiumCocker mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} items={items} onInteract={onInteract}/>")
s=s.replace("const fallback=<ProceduralPet type={type} mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} onInteract={onInteract}/>","const fallback=<ProceduralPet type={type} mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} items={items} onInteract={onInteract}/>")
rep("<HighFidelityPet type={type} mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} onInteract={interactive?onInteract:undefined}/><Wearables items={items} behavior={behavior}/>","<HighFidelityPet type={type} mood={mood} behavior={behavior} behaviorNonce={behaviorNonce} items={items} onInteract={interactive?onInteract:undefined}/><Wearables items={items} behavior={behavior} mount=\"body\"/>",'pet model mounts')
fs.writeFileSync(p,s)
console.log('V70 Mia wearable anchors applied')