import fs from 'node:fs'
import path from 'node:path'
const root=process.cwd(); const read=p=>fs.readFileSync(path.join(root,p),'utf8')
const required=['components/games/GamesHub.tsx','components/games/MiniArcade.tsx','components/games/SoloGames.tsx','components/world/WorldHub.tsx','components/world/Pet3D.tsx','components/WeeklyChallenge.tsx','components/Achievements.tsx','lib/gameCatalog.ts','lib/adventures.ts','supabase/production_v9.sql','supabase/MIGRAR_DESDE_V8_A_V9.sql','supabase/ACTUALIZAR_DESDE_VERSION_ORIGINAL.sql']
for(const f of required)if(!fs.existsSync(path.join(root,f)))throw new Error(`Falta ${f}`)
const catalog=read('lib/gameCatalog.ts'),hub=read('components/games/GamesHub.tsx'),solo=read('components/games/SoloGames.tsx'),sql=read('supabase/production_v9.sql'),mig=read('supabase/MIGRAR_DESDE_V8_A_V9.sql'),css=read('app/globals.css'),dashboard=read('components/Dashboard.tsx'),world=read('components/world/WorldHub.tsx'),pet3d=read('components/world/Pet3D.tsx'),pkg=JSON.parse(read('package.json'))
const expected=['mind-meld','would-you-rather','know-me','likely','either-or','truth-dare','roulette','two-truths','taboo','draw','word-chain','code4','puzzle','trivia-coop','trivia-versus','cards','adventure','escape','bomb','reaction','pong','air-hockey','snake-duo','turbo-race','block-drop']
const ids=[...catalog.matchAll(/id:'([^']+)'/g)].map(m=>m[1]); for(const id of expected)if(!ids.includes(id))throw new Error(`Juego ausente: ${id}`)
const soloExpected=['memory','2048','snake','trivia-solo','reaction-solo','word-scramble','tap-rush','block-solo'];for(const id of soloExpected)if(!solo.includes(`id:'${id}'`))throw new Error(`Juego individual ausente: ${id}`)
for(const dep of ['three','@react-three/fiber','@react-three/drei'])if(!pkg.dependencies?.[dep])throw new Error(`Falta dependencia 3D: ${dep}`)
for(const pet of ['Cocker','Panda','Shiba','Capybara'])if(!pet3d.includes(`function ${pet}`))throw new Error(`Falta modelo 3D: ${pet}`)
for(const rpc of ['pet_refresh_state','pet_interact','adopt_pet','update_pet_profile','start_game_session','submit_game_turn','start_solo_game','finish_solo_game'])if(!sql.includes(`function public.${rpc}`))throw new Error(`Falta RPC: ${rpc}`)
if(/nav[^\n]{0,180}Recuerdos/i.test(dashboard))throw new Error('Recuerdos sigue expuesto')
if(!sql.includes('game_sessions_one_open_game_idx')||!mig.includes('game_sessions_one_open_game_idx'))throw new Error('Falta restricción de una partida activa por juego')
if(!sql.includes('exception when unique_violation')||!sql.includes("game_type=p_game_type and status in ('active','waiting')"))throw new Error('start_game_session no recupera partida existente de forma segura')
for(const pair of [["'know-me'",'needed:=5'],["'mind-meld'",'needed:=5'],["'either-or'",'needed:=8'],["'trivia-coop'",'needed:=7']])if(!sql.includes(pair[0])||!sql.includes(pair[1]))throw new Error(`Falta condición de rondas ${pair[0]}`)
for(const marker of ['question_indices','prompt_indices','recentIndices','sampleIndices','Pregunta ${current} de ${target}','La partida avanzó automáticamente'])if(!hub.includes(marker))throw new Error(`Falta motor multipregunta/no repetición: ${marker}`)
for(const marker of ['VERSUS_IDS','⚔️ 1 VS 1','Cooperativos','Jugar solo','game-hub-v9','continue-hero','mode-lanes'])if(!hub.includes(marker)&&!css.includes(marker))throw new Error(`Falta hub gaming V9: ${marker}`)
if((catalog.match(/¿Qué plan escogería hoy\?/g)||[]).length!==1)throw new Error('Banco de preguntas inconsistente')
const knowBlock=catalog.slice(catalog.indexOf("'know-me': ["),catalog.indexOf("  ]\n}",catalog.indexOf("'know-me': [")));const knowCount=(knowBlock.match(/\{q:/g)||[]).length;if(knowCount<35)throw new Error(`Banco know-me demasiado pequeño: ${knowCount}`)
if(hub.includes('＋ Nueva</button>'))throw new Error('Nueva partida sigue disponible dentro de una sesión activa')
if(!hub.includes('La revancha crea una partida nueva con contenido distinto'))throw new Error('Falta revancha post-partida')
if(!sql.includes("action_type='word')<10"))throw new Error('Cadena no exige 10 turnos en backend')
if(!hub.includes('entries.length>=10'))throw new Error('Cadena no muestra finalización a 10 turnos')
if(!sql.includes('daily_limit')||!sql.includes('same_count>=3')||!sql.includes('today_count>=12'))throw new Error('Faltan límites anti-farmeo')
if(!sql.includes('pet_sex text')||!world.includes('♀️ Hembra')||!world.includes('♂️ Macho'))throw new Error('Falta sexo de mascota V6+')
if(solo.includes('const QS=['))throw new Error('Trivia individual todavía usa preguntas fijas')
for(const marker of ['randomTrivia(5)','trivia-feedback','La respuesta correcta es','trivia-pair-feedback','Correcta:'])if(!solo.includes(marker)&&!hub.includes(marker)&&!css.includes(marker))throw new Error(`Falta feedback/no repetición V13: ${marker}`)
console.log(`OK V13: ${expected.length} juegos de pareja + ${soloExpected.length} individuales; trivia aleatoria con feedback; contenido con menor repetición; motor de rondas y Pet Life 3D intactos.`)
