'use client'
import React,{useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {CARD_DECK,CHOICE_QUESTIONS,DRAW_WORDS,GAME_CATALOG,MIND_PROMPTS,TABOO_CARDS,TRIVIA,TRUTH_DARES,GameDef} from '@/lib/gameCatalog'
import {ADVENTURES,ESCAPES} from '@/lib/adventures'
import DrawingBoard,{Stroke} from './DrawingBoard'
import {LiveAirHockey,LivePong,LiveSnakeDuo,LiveTurboRace,ReactionGame} from './MiniArcade'

type Session={id:string;couple_id:string;game_type:string;mode:string;status:string;created_by:string;state:any;created_at:string;updated_at:string;expires_at:string}
type Turn={id:string;session_id:string;user_id:string;round_no:number;action_type:string;payload:any;created_at:string}

function hashIndex(id:string,n:number){let h=2166136261;for(const c of id){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return n?Math.abs(h)%n:0}
function gameBy(id:string){return GAME_CATALOG.find(g=>g.id===id)??GAME_CATALOG[0]}
function normalize(s:string){return s.trim().toLocaleLowerCase('es-PE').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}

export default function GamesHub({coupleId,userId,partnerName='Tu persona',onPoints}:{coupleId:string;userId:string;partnerName?:string;onPoints?:(n:number)=>void}){
 const s=useMemo(()=>createClient(),[])
 const [view,setView]=useState<'home'|'catalog'|'pending'>('home');const [selected,setSelected]=useState<GameDef|null>(null);const [session,setSession]=useState<Session|null>(null);const [turns,setTurns]=useState<Turn[]>([]);const [pending,setPending]=useState<Session[]>([]);const [pendingLast,setPendingLast]=useState<Record<string,string>>({});const [presence,setPresence]=useState(false);const [filter,setFilter]=useState<'all'|'async'|'live'>('all');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{loadPending();const ch=s.channel(`games-${coupleId}`,{config:{presence:{key:userId}}}).on('postgres_changes',{event:'*',schema:'public',table:'game_sessions',filter:`couple_id=eq.${coupleId}`},()=>loadPending()).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_turns',filter:`couple_id=eq.${coupleId}`},payload=>{if(session&&payload.new?.session_id===session.id)loadTurns(session.id)}).on('presence',{event:'sync'},()=>{const st=ch.presenceState();setPresence(Object.values(st).flat().length>1)}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.track({user_id:userId,at:new Date().toISOString()})});return()=>{s.removeChannel(ch)}},[coupleId,userId,session?.id])
 async function loadPending(){const {data}=await s.from('game_sessions').select('*').eq('couple_id',coupleId).in('status',['active','waiting']).gte('expires_at',new Date().toISOString()).order('updated_at',{ascending:false}).limit(30);const sessions=(data||[]) as Session[];setPending(sessions);if(!sessions.length){setPendingLast({});return}const ids=sessions.map(x=>x.id);const {data:ts}=await s.from('game_turns').select('session_id,user_id,created_at').in('session_id',ids).order('created_at',{ascending:true});const map:Record<string,string>={};(ts||[]).forEach((t:any)=>map[t.session_id]=t.user_id);setPendingLast(map)}
 async function loadTurns(id:string){const {data}=await s.from('game_turns').select('*').eq('session_id',id).order('created_at',{ascending:true}).order('id',{ascending:true});setTurns((data||[]) as Turn[])}
 function initialState(g:GameDef){const seed=crypto.randomUUID();if(CHOICE_QUESTIONS[g.id])return{question_index:hashIndex(seed,CHOICE_QUESTIONS[g.id].length)};if(g.id==='mind-meld')return{prompt_index:hashIndex(seed,MIND_PROMPTS.length)};if(g.id.startsWith('trivia'))return{question_index:hashIndex(seed,TRIVIA.length)};if(g.id==='cards')return{card_index:hashIndex(seed,CARD_DECK.length)};if(g.id==='truth-dare'||g.id==='roulette')return{card_index:hashIndex(seed,TRUTH_DARES.length)};if(g.id==='draw')return{word:DRAW_WORDS[hashIndex(seed,DRAW_WORDS.length)]};if(g.id==='taboo')return TABOO_CARDS[hashIndex(seed,TABOO_CARDS.length)];if(g.id==='word-chain')return{word:['CASA','LUNA','RÍO','MESA','SOL'][hashIndex(seed,5)]};if(g.id==='code4')return{secret:Array.from({length:4},(_,i)=>hashIndex(seed+i,6))};if(g.id==='puzzle')return{tiles:[1,2,3,4,5,6,0,7,8]};if(g.id==='adventure')return{adventure_id:ADVENTURES[hashIndex(seed,ADVENTURES.length)].id};if(g.id==='escape')return{escape_id:ESCAPES[hashIndex(seed,ESCAPES.length)].id};if(g.id==='block-drop')return{board:Array(25).fill(0)};return{seed}}
 async function startGame(g:GameDef){setMessage('');if(g.mode==='live'&&!presence)setMessage(`${g.title} es en vivo. La sala quedará lista y puedes esperar a ${partnerName}.`);setBusy(true);const {data,error}=await s.rpc('start_game_session',{p_game_type:g.id,p_mode:g.mode,p_state:initialState(g)});setBusy(false);if(error){setMessage('No pudimos crear la partida: '+error.message);return}setSelected(g);setSession(data as Session);setTurns([]);loadPending()}
 async function openSession(ss:Session){setSession(ss);setSelected(gameBy(ss.game_type));await loadTurns(ss.id)}
 async function addTurn(action_type:string,payload:any){if(!session)return false;setMessage('');const {error}=await s.rpc('submit_game_turn',{p_session_id:session.id,p_action_type:action_type,p_payload:payload});if(error){const text=(error.message||'').toUpperCase();setMessage(text.includes('WAIT_FOR_PARTNER')?`Ahora le toca a ${partnerName}.`:text.includes('ALREADY_ANSWERED')?'Tu respuesta ya quedó guardada.':'No pudimos guardar el turno: '+error.message);return false}await loadTurns(session.id);loadPending();return true}
 async function finish(){if(!session)return;setBusy(true);setMessage('');const {data,error}=await s.rpc('finish_game_session',{p_session_id:session.id});setBusy(false);if(error){const text=(error.message||'').toUpperCase();setMessage(text.includes('WAIT_FOR_PARTNER')?`Falta la participación de ${partnerName}.`:text.includes('PLAY_A_LITTLE_LONGER')?'Jueguen un poquito más antes de cerrar la partida.':'La partida todavía no cumple las condiciones para terminar: '+error.message);return}onPoints?.(Number(data||0));setSession(null);setSelected(null);setTurns([]);loadPending()}
 async function abandon(){if(!session)return;if(!confirm('¿Cerrar esta partida sin puntos?'))return;await s.rpc('abandon_game_session',{p_session_id:session.id});setSession(null);setSelected(null);setTurns([]);loadPending()}
 if(session&&selected)return <GameRoom game={selected} session={session} turns={turns} userId={userId} partnerName={partnerName} message={message} busy={busy} onTurn={addTurn} onFinish={finish} onBack={()=>{setSession(null);setSelected(null);setTurns([]);setMessage('')}} onAbandon={abandon}/>
 const shown=GAME_CATALOG.filter(g=>filter==='all'||g.mode===filter||g.mode==='both')
 return <div className="game-shell">
  <div className="game-hero"><div><div className="eyebrow">Jugar</div><h1>¿Qué jugamos hoy?</h1><p>Juegos que pueden esperar horas o días, más arcades para cuando coincidan.</p></div><div className={`presence ${presence?'online':''}`}><span/> {presence?`${partnerName} está aquí`:'Modo asíncrono listo'}</div></div>
  {message&&<div className="notice">{message}</div>}
  <div className="game-subnav"><button className={view==='home'?'active':''} onClick={()=>setView('home')}>Para hoy</button><button className={view==='catalog'?'active':''} onClick={()=>setView('catalog')}>Todos los juegos</button><button className={view==='pending'?'active':''} onClick={()=>setView('pending')}>Partidas <b>{pending.length}</b></button></div>
  {view==='home'&&<><section className="play-now"><div><span className="tag">⚡ 2–5 min</span><h2>Una partida sin pensarlo mucho</h2><p className="muted">Empieza ahora. Si la otra persona no está, el turno queda guardado.</p></div><button className="btn game-primary" disabled={busy} onClick={()=>startGame(GAME_CATALOG[hashIndex(new Date().toDateString(),17)])}>Jugar ahora</button></section>
   {pending.length>0&&<section><div className="section-title"><h2>Partidas abiertas</h2><button onClick={()=>setView('pending')}>Ver todas</button></div><div className="game-grid compact">{pending.slice(0,4).map(p=><GameCard key={p.id} game={gameBy(p.game_type)} badge={turnBadge(p,pendingLast,userId)} onClick={()=>openSession(p)}/>)}</div></section>}
   <section><div className="section-title"><h2>Favoritos para empezar</h2><span>Asíncronos primero</span></div><div className="game-grid">{['mind-meld','would-you-rather','draw','trivia-coop','cards','adventure','escape','puzzle'].map(id=><GameCard key={id} game={gameBy(id)} onClick={()=>startGame(gameBy(id))}/>)}</div></section>
   <section className="live-strip"><div><span className="live-dot"/> <b>Juntos ahora</b><p>{presence?'Los dos están conectados. Los arcades ya pueden empezar.':'Cuando ambos estén aquí, abran la misma partida.'}</p></div><div className="actions"><button className="btn secondary" onClick={()=>startGame(gameBy('reaction'))}>⚡ Reacción</button><button className="btn secondary" onClick={()=>startGame(gameBy('pong'))}>🏓 Pong</button><button className="btn secondary" onClick={()=>startGame(gameBy('snake-duo'))}>🐍 Snake</button></div></section></>}
  {view==='catalog'&&<><div className="filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todos</button><button className={filter==='async'?'active':''} onClick={()=>setFilter('async')}>Por turnos</button><button className={filter==='live'?'active':''} onClick={()=>setFilter('live')}>En vivo</button></div><div className="game-grid">{shown.map(g=><GameCard key={g.id} game={g} onClick={()=>startGame(g)}/>)}</div></>}
  {view==='pending'&&<div>{pending.length===0?<div className="empty-state"><div>🎮</div><h2>No hay partidas pendientes</h2><p>Empieza una y la otra persona podrá continuar después.</p></div>:<div className="game-grid">{pending.map(p=><GameCard key={p.id} game={gameBy(p.game_type)} badge={turnBadge(p,pendingLast,userId)} onClick={()=>openSession(p)}/>)}</div>}</div>}
 </div>
}
function turnBadge(s:Session,last:Record<string,string>,userId:string){const u=last[s.id];if(!u)return 'Tu turno';return u===userId?'Esperando':'Tu turno'}
function GameCard({game,onClick,badge}:{game:GameDef;onClick:()=>void|Promise<void>;badge?:string}){return <button className={`game-card accent-${game.accent}`} onClick={onClick}><div className="game-icon">{game.emoji}</div><div><div className="game-meta"><span>{game.mode==='live'?'EN VIVO':game.mode==='async'?'POR TURNOS':'AMBOS'} · {game.minutes}</span>{badge&&<b>{badge}</b>}</div><h3>{game.title}</h3><p>{game.description}</p></div><span className="game-arrow">→</span></button>}

type GameRoomProps={game:GameDef;session:Session;turns:Turn[];userId:string;partnerName:string;message:string;busy:boolean;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>;onBack:()=>void;onAbandon:()=>Promise<void>}
function GameRoom({game,session,turns,userId,partnerName,message,busy,onTurn,onFinish,onBack,onAbandon}:GameRoomProps){
 const mine=turns.filter(t=>t.user_id===userId),theirs=turns.filter(t=>t.user_id!==userId)
 const top=<div className="game-room-top"><button className="round-back" onClick={onBack}>← Jugar</button><div><span>{game.emoji}</span><b>{game.title}</b></div><button className="round-finish" onClick={onAbandon}>Abandonar</button></div>
 const wrap=(child:React.ReactNode)=><div className="game-room">{top}{message&&<div className="notice room-notice">{message}</div>}{child}</div>
 if(CHOICE_QUESTIONS[game.id]){const list=CHOICE_QUESTIONS[game.id],q=list[(session.state?.question_index??0)%list.length],my=mine.find(t=>t.action_type==='choice')?.payload?.choice,other=theirs.find(t=>t.action_type==='choice')?.payload?.choice;return wrap(<div className="round-card"><span className="tag">🔒 Se revela cuando ambos respondan</span><h2>{q.q}</h2><div className="choice-grid">{q.options.map(o=><button key={o} disabled={!!my||busy} className={my===o?'chosen':''} onClick={()=>onTurn('choice',{choice:o})}>{o}</button>)}</div>{my&&!other&&<Waiting name={partnerName}/>} {my&&other&&<Reveal a={my} b={other} match={my===other} onFinish={onFinish}/>}</div>)}
 if(game.id==='mind-meld')return <TextMatch top={top} message={message} prompt={MIND_PROMPTS[(session.state?.prompt_index??0)%MIND_PROMPTS.length]} mine={mine} theirs={theirs} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='trivia-coop'||game.id==='trivia-versus'){const q=TRIVIA[(session.state?.question_index??0)%TRIVIA.length],my=mine.find(t=>t.action_type==='trivia')?.payload?.answer,other=theirs.find(t=>t.action_type==='trivia')?.payload?.answer;return wrap(<div className="round-card"><span className="tag">{game.id==='trivia-coop'?'🤝 Equipo':'🏁 Versus'} · {q.cat}</span><h2>{q.q}</h2><div className="choice-grid">{q.o.map((o,i)=><button key={o} disabled={my!==undefined||busy} className={my===i?'chosen':''} onClick={()=>onTurn('trivia',{answer:i})}>{o}</button>)}</div>{my!==undefined&&other===undefined&&<Waiting name={partnerName}/>} {my!==undefined&&other!==undefined&&<div className="reveal"><div className="reveal-burst">{my===q.a&&other===q.a?'🤝':'🏁'}</div><h3>{q.o[q.a]} era la correcta</h3><p>Tú: {my===q.a?'✅':'❌'} · {partnerName}: {other===q.a?'✅':'❌'}</p><button className="btn" onClick={onFinish}>Cerrar ronda</button></div>}</div>)}
 if(game.id==='cards'){const c=CARD_DECK[(session.state?.card_index??0)%CARD_DECK.length];return wrap(<div className="card-stage"><div className="play-card"><span>{c.type}</span><p>{c.text}</p><small>Háganlo a su ritmo. No hay respuesta correcta.</small></div><button className="btn" disabled={busy} onClick={async()=>{await onTurn('complete',{card:c.type});await onFinish()}}>Hecho</button></div>)}
 if(game.id==='draw')return <DrawRoom top={top} message={message} session={session} mine={mine} theirs={theirs} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='two-truths')return <TwoTruths top={top} message={message} mine={mine} theirs={theirs} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='taboo')return <Taboo top={top} message={message} state={session.state} mine={mine} theirs={theirs} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='word-chain')return <WordChain top={top} message={message} start={session.state?.word||'CASA'} turns={turns} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='code4')return <Code4 top={top} message={message} secret={session.state?.secret||[1,2,3,4]} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='puzzle')return <Puzzle top={top} message={message} turns={turns} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='block-drop')return <BlockDrop top={top} message={message} turns={turns} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='adventure')return <AdventureRoom top={top} message={message} session={session} turns={turns} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='escape')return <EscapeRoom top={top} message={message} session={session} turns={turns} userId={userId} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='truth-dare'||game.id==='roulette')return <Roulette top={top} message={message} truth={game.id==='truth-dare'} cardIndex={session.state?.card_index||0} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='reaction')return <ReactionRoom top={top} message={message} mine={mine} theirs={theirs} partnerName={partnerName} onTurn={onTurn} onFinish={onFinish}/>
 if(game.id==='pong')return wrap(<div className="round-card wide"><LivePong sessionId={session.id} userId={userId} hostId={session.created_by}/><button className="btn" onClick={async()=>{await onTurn('complete',{mode:'live'});await onFinish()}}>Terminar partida</button></div>)
 if(game.id==='air-hockey')return wrap(<div className="round-card wide"><LiveAirHockey sessionId={session.id} userId={userId} hostId={session.created_by}/><button className="btn" onClick={async()=>{await onTurn('complete',{mode:'live'});await onFinish()}}>Terminar partida</button></div>)
 if(game.id==='snake-duo')return wrap(<div className="round-card wide"><LiveSnakeDuo sessionId={session.id} userId={userId} hostId={session.created_by}/><button className="btn" onClick={async()=>{await onTurn('complete',{mode:'live'});await onFinish()}}>Terminar partida</button></div>)
 if(game.id==='turbo-race')return wrap(<div className="round-card wide"><LiveTurboRace sessionId={session.id} userId={userId}/><button className="btn" onClick={async()=>{await onTurn('complete',{mode:'live'});await onFinish()}}>Terminar partida</button></div>)
 if(game.id==='bomb')return <Bomb top={top} message={message} onTurn={onTurn} onFinish={onFinish}/>
 return wrap(<div className="round-card"><h2>{game.title}</h2><p>Juego listo en el motor común.</p></div>)
}

function Waiting({name}:{name:string}){return <div className="waiting"><div className="typing"><i/><i/><i/></div><div><b>Tu turno quedó guardado</b><p>Esperando a {name}. Puede responder más tarde.</p></div></div>}
function Reveal({a,b,match,onFinish}:{a:any;b:any;match:boolean;onFinish:()=>Promise<void>}){return <div className="reveal"><div className="reveal-burst">{match?'✨':'👀'}</div><h3>{match?'¡Coincidieron!':'Pensaron diferente'}</h3><div className="versus-answer"><span>Tú<b>{String(a)}</b></span><span>La otra persona<b>{String(b)}</b></span></div><button className="btn" onClick={onFinish}>Cerrar ronda</button></div>}
function Notice({message}:{message:string}){return message?<div className="notice room-notice">{message}</div>:null}

function TextMatch({top,message,prompt,mine,theirs,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;prompt:string;mine:Turn[];theirs:Turn[];partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [text,setText]=useState('');const my=mine.find(t=>t.action_type==='text')?.payload?.text,other=theirs.find(t=>t.action_type==='text')?.payload?.text;return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><span className="tag">🧠 Misma palabra = coincidencia</span><h2>{prompt}</h2>{!my&&<><input className="game-input" maxLength={80} value={text} onChange={e=>setText(e.target.value)} placeholder="Una palabra…"/><button className="btn" disabled={!text.trim()} onClick={()=>onTurn('text',{text:text.trim()})}>Bloquear respuesta</button></>}{my&&!other&&<Waiting name={partnerName}/>} {my&&other&&<Reveal a={my} b={other} match={normalize(my)===normalize(other)} onFinish={onFinish}/>}</div></div>}

function DrawRoom({top,message,session,mine,theirs,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;session:Session;mine:Turn[];theirs:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [strokes,setStrokes]=useState<Stroke[]>([]),[guess,setGuess]=useState('');const drawingTurn=turnsByAction([...mine,...theirs],'drawing')[0];const drawing=drawingTurn?.payload?.strokes;const myGuess=mine.find(t=>t.action_type==='guess');const otherGuess=theirs.find(t=>t.action_type==='guess');if(!drawing)return <div className="game-room">{top}<Notice message={message}/><div className="round-card wide"><span className="tag">Tu palabra: {session.state?.word}</span><h2>Dibújalo sin letras</h2><DrawingBoard value={strokes} onChange={setStrokes}/><button className="btn" disabled={strokes.length<2} onClick={()=>onTurn('drawing',{strokes})}>Enviar dibujo</button></div></div>;const amDrawer=drawingTurn.user_id===userId; if(!amDrawer&&!myGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card wide"><h2>¿Qué dibujó {partnerName}?</h2><DrawingBoard value={drawing} readonly/><input className="game-input" value={guess} maxLength={50} onChange={e=>setGuess(e.target.value)} placeholder="Tu respuesta"/><button className="btn" disabled={!guess.trim()} onClick={()=>onTurn('guess',{guess:guess.trim()})}>Adivinar</button></div></div>;if(amDrawer&&!otherGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card wide"><DrawingBoard value={drawing} readonly/><Waiting name={partnerName}/></div></div>;const guessTurn=myGuess||otherGuess;const ok=normalize(guessTurn?.payload?.guess||'')===normalize(session.state?.word||'');return <div className="game-room">{top}<Notice message={message}/><div className="round-card wide"><DrawingBoard value={drawing} readonly/><div className="reveal"><div className="reveal-burst">{ok?'🎯':'🎨'}</div><h3>{ok?'¡Adivinado!':'La palabra era '+session.state?.word}</h3><p>Respuesta: <b>{guessTurn?.payload?.guess}</b></p><button className="btn" onClick={onFinish}>Terminar</button></div></div></div>}
function turnsByAction(ts:Turn[],a:string){return ts.filter(t=>t.action_type===a)}

function TwoTruths({top,message,mine,theirs,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;mine:Turn[];theirs:Turn[];partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [vals,setVals]=useState(['','','']),[lie,setLie]=useState(2);const mineCreated=mine.find(t=>t.action_type==='statements'),otherCreated=theirs.find(t=>t.action_type==='statements'),myGuess=mine.find(t=>t.action_type==='guess'),otherGuess=theirs.find(t=>t.action_type==='guess');if(!mineCreated&&!otherCreated)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Escribe dos verdades y una mentira</h2>{vals.map((v,i)=><div className="statement-row" key={i}><input maxLength={160} value={v} onChange={e=>{const n=[...vals];n[i]=e.target.value;setVals(n)}} placeholder={`Afirmación ${i+1}`}/><label><input type="radio" checked={lie===i} onChange={()=>setLie(i)}/> mentira</label></div>)}<button className="btn" disabled={vals.some(v=>!v.trim())} onClick={()=>onTurn('statements',{items:vals.map(v=>v.trim()),lie})}>Enviar</button></div></div>;if(otherCreated&&!myGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>¿Cuál es la mentira de {partnerName}?</h2><div className="choice-grid">{otherCreated.payload.items.map((x:string,i:number)=><button key={i} onClick={()=>onTurn('guess',{index:i})}>{x}</button>)}</div></div></div>;if(mineCreated&&!otherGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><Waiting name={partnerName}/></div></div>;const guess=myGuess||otherGuess,target=myGuess?otherCreated:mineCreated;const match=!!guess&&!!target&&guess.payload.index===target.payload.lie;return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><Reveal a={`Elegiste ${Number(guess?.payload?.index)+1}`} b={`Era ${Number(target?.payload?.lie)+1}`} match={match} onFinish={onFinish}/></div></div>}

function Taboo({top,message,state,mine,theirs,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;state:any;mine:Turn[];theirs:Turn[];partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [hint,setHint]=useState(''),[guess,setGuess]=useState('');const myHint=mine.find(t=>t.action_type==='hint'),otherHint=theirs.find(t=>t.action_type==='hint'),myGuess=mine.find(t=>t.action_type==='guess'),otherGuess=theirs.find(t=>t.action_type==='guess');if(!myHint&&!otherHint)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><span className="tag">Palabra: {state.word}</span><h2>Da una pista</h2><p className="muted">No uses: {(state.forbidden||[]).join(', ')}</p><input className="game-input" maxLength={160} value={hint} onChange={e=>setHint(e.target.value)}/><button className="btn" disabled={!hint.trim()||state.forbidden?.some((x:string)=>normalize(hint).includes(normalize(x)))} onClick={()=>onTurn('hint',{hint:hint.trim()})}>Enviar pista</button></div></div>;if(otherHint&&!myGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Pista de {partnerName}</h2><div className="clue">“{otherHint.payload.hint}”</div><input className="game-input" maxLength={60} value={guess} onChange={e=>setGuess(e.target.value)}/><button className="btn" disabled={!guess.trim()} onClick={()=>onTurn('guess',{guess:guess.trim()})}>Responder</button></div></div>;if(myHint&&!otherGuess)return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><Waiting name={partnerName}/></div></div>;const g=myGuess||otherGuess;return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><Reveal a={g?.payload?.guess||''} b={state.word} match={normalize(g?.payload?.guess||'')===normalize(state.word)} onFinish={onFinish}/></div></div>}

function WordChain({top,message,start,turns,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;start:string;turns:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [word,setWord]=useState('');const entries=turns.filter(t=>t.action_type==='word'),words=[start,...entries.map(t=>t.payload.word)],last=words.at(-1)||start,lastUser=entries.at(-1)?.user_id;const myTurn=!lastUser||lastUser!==userId;const clean=word.trim();const valid=clean.length>1&&normalize(clean).startsWith(normalize(last).slice(-1))&&!words.map(normalize).includes(normalize(clean));return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Cadena de palabras</h2><div className="word-chain">{words.map((w,i)=><span key={i}>{w}</span>)}</div>{myTurn?<><p>Tu palabra debe empezar con <b>{last.slice(-1).toUpperCase()}</b>.</p><input className="game-input" maxLength={40} value={word} onChange={e=>setWord(e.target.value)}/><button className="btn" disabled={!valid} onClick={async()=>{if(await onTurn('word',{word:clean}))setWord('')}}>Agregar</button></>:<Waiting name={partnerName}/>} {entries.length>=6&&<button className="btn secondary" onClick={onFinish}>Cerrar cadena</button>}</div></div>}

function Code4({top,message,secret,onTurn,onFinish}:{top:React.ReactNode;message:string;secret:number[];onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const [guess,setGuess]=useState([0,0,0,0]),[tries,setTries]=useState<{g:number[];exact:number;near:number}[]>([]),[sent,setSent]=useState(false);const solved=tries.at(-1)?.exact===4;function test(){let exact=0;const sc=[...secret],gc=[...guess];for(let i=0;i<4;i++)if(gc[i]===sc[i]){exact++;gc[i]=-1;sc[i]=-2}let near=0;for(let i=0;i<4;i++){if(gc[i]<0)continue;const j=sc.indexOf(gc[i]);if(j>=0){near++;sc[j]=-2}}setTries([...tries,{g:[...guess],exact,near}])}async function complete(){if(!sent){await onTurn('complete',{tries:tries.length});setSent(true)}await onFinish()}return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Descifra el código</h2><p className="muted">● correcto en lugar correcto · ○ correcto en lugar distinto.</p><div className="code-row">{guess.map((v,i)=><button key={i} onClick={()=>{const n=[...guess];n[i]=(v+1)%6;setGuess(n)}}>{v+1}</button>)}</div><button className="btn" onClick={test}>Probar</button><div className="code-tries">{tries.map((t,i)=><div key={i}><span>{t.g.map(x=>x+1).join(' ')}</span><b>{'●'.repeat(t.exact)}{'○'.repeat(t.near)}</b></div>)}</div>{solved&&<button className="btn secondary" onClick={complete}>Código descubierto ✨</button>}</div></div>}

function derivePuzzle(turns:Turn[]){let tiles=[1,2,3,4,5,6,0,7,8];for(const t of turns.filter(x=>x.action_type==='puzzle_move')){const i=Number(t.payload.index),z=tiles.indexOf(0),r=Math.floor(i/3),zr=Math.floor(z/3);if(Number.isInteger(i)&&i>=0&&i<9&&(Math.abs(i-z)===3||(r===zr&&Math.abs(i-z)===1))){const n=[...tiles];[n[i],n[z]]=[n[z],n[i]];tiles=n}}return tiles}
function Puzzle({top,message,turns,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;turns:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const tiles=derivePuzzle(turns),moves=turns.filter(t=>t.action_type==='puzzle_move'),last=moves.at(-1)?.user_id,myTurn=!last||last!==userId,solved=tiles.join(',')==='1,2,3,4,5,6,7,8,0';async function move(i:number){const z=tiles.indexOf(0),r=Math.floor(i/3),zr=Math.floor(z/3);if(myTurn&&(Math.abs(i-z)===3||(r===zr&&Math.abs(i-z)===1)))await onTurn('puzzle_move',{index:i})}async function done(){await onTurn('complete',{moves:moves.length});await onFinish()}return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Puzzle cooperativo 3×3</h2><p className="muted">Cada movimiento se guarda. Después de mover, le toca a {partnerName}.</p><div className="puzzle-grid">{tiles.map((t,i)=><button key={i} disabled={!myTurn||t===0} className={t===0?'blank':''} onClick={()=>move(i)}>{t||''}</button>)}</div>{!myTurn&&!solved&&<Waiting name={partnerName}/>} {solved&&<button className="btn" onClick={done}>¡Completado!</button>}</div></div>}

function BlockDrop({top,message,turns,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;turns:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const moves=turns.filter(t=>t.action_type==='block'),filled=new Set<number>(moves.map(t=>Number(t.payload.cell))),last=moves.at(-1)?.user_id,myTurn=!last||last!==userId;const completedRows=[0,1,2,3,4].filter(r=>[0,1,2,3,4].every(c=>filled.has(r*5+c)));async function place(cell:number){if(!filled.has(cell)&&myTurn)await onTurn('block',{cell})}async function done(){await onTurn('complete',{rows:completedRows.length});await onFinish()}return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Block Drop cooperativo</h2><p>Alternen colocando bloques. Completen al menos una línea horizontal.</p><div className="block-grid">{Array.from({length:25},(_,i)=><button key={i} disabled={!myTurn||filled.has(i)} className={filled.has(i)?'filled':''} onClick={()=>place(i)}/>)}</div>{!myTurn&&<Waiting name={partnerName}/>} {completedRows.length>0&&<button className="btn" onClick={done}>Completar línea ✨</button>}</div></div>}

function AdventureRoom({top,message,session,turns,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;session:Session;turns:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const adventure=ADVENTURES.find(a=>a.id===session.state?.adventure_id)||ADVENTURES[0],choices=turns.filter(t=>t.action_type==='adventure_choice'),end=turns.find(t=>t.action_type==='adventure_end');let node=adventure.nodes[adventure.start];for(const t of choices){const choice=node.choices?.[Number(t.payload.index)];if(!choice)break;node=adventure.nodes[choice.next]}const last=choices.at(-1)?.user_id,myTurn=!last||last!==userId;if(end)return <div className="game-room adventure-bg">{top}<Notice message={message}/><div className="story-card"><span>{adventure.subtitle}</span><h2>{node.title}</h2><p>{node.text}</p><div className="ending-badge">{node.ending}</div><button className="btn" onClick={onFinish}>Guardar final</button></div></div>;async function choose(i:number){const next=node.choices?.[i];if(!next)return;const nextNode=adventure.nodes[next.next];await onTurn('adventure_choice',{node:node.id,index:i,next:next.next});if(nextNode.ending)await onTurn('adventure_end',{ending:nextNode.ending,node:nextNode.id})}return <div className="game-room adventure-bg">{top}<Notice message={message}/><div className="story-card"><span>{adventure.title} · decisión {choices.length+1}</span><h2>{node.title}</h2><p>{node.text}</p>{node.choices?.map((o,i)=><button key={o.label} disabled={!myTurn} onClick={()=>choose(i)}>{o.label}<b>→</b></button>)}{!myTurn&&<Waiting name={partnerName}/>}</div></div>}

function EscapeRoom({top,message,session,turns,userId,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;session:Session;turns:Turn[];userId:string;partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const scenario=ESCAPES.find(e=>e.id===session.state?.escape_id)||ESCAPES[0],found=turns.filter(t=>t.action_type==='escape_clue').map(t=>String(t.payload.object)),solved=turns.some(t=>t.action_type==='escape_solved'),[code,setCode]=useState('');async function find(id:string){if(!found.includes(id))await onTurn('escape_clue',{object:id})}async function tryCode(){if(code===scenario.code)await onTurn('escape_solved',{code});else await onTurn('escape_attempt',{length:code.length})}return <div className="game-room escape-bg">{top}<Notice message={message}/><div className="escape-room"><span className="tag">{scenario.subtitle}</span><h2>{scenario.title}</h2>{!solved?<><p>Toquen objetos, compartan pistas y abran el cierre.</p><div className="room-scene escape-objects">{scenario.objects.map(o=><button key={o.id} className={`escape-object ${found.includes(o.id)?'found':''}`} onClick={()=>find(o.id)}><span>{o.emoji}</span><small>{o.name}</small></button>)}<div className="safe">🔒</div></div><div className="inventory">{scenario.objects.filter(o=>found.includes(o.id)).map(o=><span key={o.id}>🔎 {o.clue}</span>)}</div><input className="game-input" inputMode="numeric" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="Código"/><button className="btn" disabled={code.length<3} onClick={tryCode}>Probar código</button><p className="tiny">Las pistas encontradas quedan visibles para ambos incluso si entran en horas distintas.</p></>:<div className="reveal"><div className="reveal-burst">🗝️</div><h3>¡Sala resuelta!</h3><p>{scenario.finalText}</p><button className="btn" onClick={onFinish}>Cerrar caso</button></div>}</div></div>}

function Roulette({top,message,truth,cardIndex,onTurn,onFinish}:{top:React.ReactNode;message:string;truth:boolean;cardIndex:number;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const options=truth?['Verdad','Reto','Verdad','Reto','Sorpresa','Elige el otro']:['Pregunta','Reto','Comida','Película','Sorpresa','Elección'];const [rot,setRot]=useState(0),[pick,setPick]=useState(''),[text,setText]=useState('');function spin(){const idx=Math.floor(Math.random()*options.length);setRot(r=>r+720+idx*60);setPick('');setTimeout(()=>{setPick(options[idx]);const card=TRUTH_DARES[(cardIndex+idx)%TRUTH_DARES.length];setText(truth?card.text:idx===0?'¿Qué lugar nuevo visitarían este mes?':idx===1?'Hagan una pose absurda durante 15 segundos.':idx===2?'Elijan una comida para compartir.':idx===3?'Elijan una película sin mirar puntuaciones.':'El otro decide la siguiente ronda.')},720)}async function done(){await onTurn('complete',{result:pick});await onFinish()}return <div className="game-room">{top}<Notice message={message}/><div className="round-card roulette-wrap"><div className="roulette-pointer">▼</div><div className="roulette-wheel" style={{transform:`rotate(${rot}deg)`}}>{options.map((o,i)=><span key={o+i} style={{transform:`rotate(${i*60}deg) translateY(-92px) rotate(${-i*60}deg)`}}>{o}</span>)}</div><button className="btn" onClick={spin}>Girar</button>{pick&&<div className="clue"><b>{pick}</b><br/>{text}</div>} {pick&&<button className="btn secondary" onClick={done}>Hecho</button>}</div></div>}

function ReactionRoom({top,message,mine,theirs,partnerName,onTurn,onFinish}:{top:React.ReactNode;message:string;mine:Turn[];theirs:Turn[];partnerName:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const my=mine.find(t=>t.action_type==='reaction')?.payload?.ms,other=theirs.find(t=>t.action_type==='reaction')?.payload?.ms;return <div className="game-room">{top}<Notice message={message}/><div className="round-card"><h2>Reaction Duel</h2>{my===undefined?<ReactionGame onScore={ms=>onTurn('reaction',{ms})}/>:other===undefined?<Waiting name={partnerName}/>:<div className="reveal"><div className="reveal-burst">⚡</div><h3>{my<other?'Ganaste esta ronda':my===other?'Empate perfecto':'Ganó '+partnerName}</h3><div className="versus-answer"><span>Tú<b>{my} ms</b></span><span>{partnerName}<b>{other} ms</b></span></div><button className="btn" onClick={onFinish}>Cerrar duelo</button></div>}</div></div>}

function Bomb({top,message,onTurn,onFinish}:{top:React.ReactNode;message:string;onTurn:(a:string,p:any)=>Promise<boolean>;onFinish:()=>Promise<void>}){const categories=['Países con C','Animales con M','Comidas que llevan queso','Películas de una palabra','Cosas que hay en una cocina','Ciudades de Sudamérica','Objetos rojos','Profesiones'],[category]=useState(()=>categories[Math.floor(Math.random()*categories.length)]),[running,setRunning]=useState(false),[boom,setBoom]=useState(false);useEffect(()=>{if(!running)return;const t=setTimeout(()=>{setBoom(true);setRunning(false);navigator.vibrate?.([120,60,180])},3000+Math.random()*6500);return()=>clearTimeout(t)},[running]);async function done(){await onTurn('complete',{category});await onFinish()}return <div className="game-room">{top}<Notice message={message}/><div className="round-card bomb-card"><div className={boom?'bomb boom':'bomb'}>💣</div><h2>{boom?'¡BOOM!':category}</h2><p>Pásense el turno verbalmente. El temporizador cambia en cada ronda.</p><button className="btn" disabled={running} onClick={()=>{setBoom(false);setRunning(true)}}>{running?'Corriendo…':'Iniciar bomba'}</button>{boom&&<button className="btn secondary" onClick={done}>Terminar</button>}</div></div>}
