'use client'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
export function ReactionGame({onScore}:{onScore:(ms:number)=>void}){const [phase,setPhase]=useState<'idle'|'wait'|'go'|'done'>('idle');const [msg,setMsg]=useState('Toca iniciar');const start=useRef(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null)
 function begin(){setPhase('wait');setMsg('Espera…');timer.current=setTimeout(()=>{start.current=performance.now();setPhase('go');setMsg('¡AHORA!')},1200+Math.random()*2600)}
 function hit(){if(phase==='idle'||phase==='done')return begin();if(phase==='wait'){if(timer.current)clearTimeout(timer.current);setPhase('done');setMsg('Muy pronto 😅 · toca para reiniciar');return}const ms=Math.round(performance.now()-start.current);setMsg(`${ms} ms · toca para otra`);setPhase('done');onScore(ms)}
 return <button className={`reaction-pad ${phase}`} onClick={hit}>{msg}</button>}
export function PongGame(){const canvas=useRef<HTMLCanvasElement>(null);const [score,setScore]=useState([0,0]);const y=useRef(210);const ai=useRef(210);const ball=useRef({x:320,y:210,vx:4.4,vy:3.2});useEffect(()=>{let id=0;const c=canvas.current!,ctx=c.getContext('2d')!;function loop(){const b=ball.current;b.x+=b.vx;b.y+=b.vy;if(b.y<8||b.y>412)b.vy*=-1;ai.current+=(b.y-ai.current)*.055;if(b.x<35&&Math.abs(b.y-y.current)<60)b.vx=Math.abs(b.vx)*1.015;if(b.x>605&&Math.abs(b.y-ai.current)<60)b.vx=-Math.abs(b.vx)*1.015;if(b.x<0){setScore(s=>[s[0],s[1]+1]);ball.current={x:320,y:210,vx:4.4,vy:3.2}}if(b.x>640){setScore(s=>[s[0]+1,s[1]]);ball.current={x:320,y:210,vx:-4.4,vy:-3.2}}ctx.clearRect(0,0,640,420);ctx.fillStyle='#2c2832';ctx.fillRect(0,0,640,420);ctx.fillStyle='#fff';ctx.globalAlpha=.2;for(let yy=0;yy<420;yy+=30)ctx.fillRect(318,yy,4,17);ctx.globalAlpha=1;ctx.fillRect(18,y.current-50,12,100);ctx.fillRect(610,ai.current-50,12,100);ctx.beginPath();ctx.arc(b.x,b.y,9,0,Math.PI*2);ctx.fill();id=requestAnimationFrame(loop)}loop();return()=>cancelAnimationFrame(id)},[])
 return <div><div className="arcade-score">Tú {score[0]} — {score[1]} Rival</div><canvas ref={canvas} width={640} height={420} className="arcade-canvas" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();y.current=(e.clientY-r.top)*420/r.height}}/></div>}
export function AirHockey(){const canvas=useRef<HTMLCanvasElement>(null);const player=useRef({x:320,y:340});const puck=useRef({x:320,y:210,vx:3.2,vy:3.8});const [score,setScore]=useState([0,0]);useEffect(()=>{let id=0;const c=canvas.current!,ctx=c.getContext('2d')!;function loop(){const p=puck.current;p.x+=p.vx;p.y+=p.vy;if(p.x<18||p.x>622)p.vx*=-1;if(p.y<0){setScore(s=>[s[0]+1,s[1]]);Object.assign(p,{x:320,y:210,vx:3.2,vy:3.8})}if(p.y>420){setScore(s=>[s[0],s[1]+1]);Object.assign(p,{x:320,y:210,vx:-3.2,vy:-3.8})}const dx=p.x-player.current.x,dy=p.y-player.current.y,d=Math.hypot(dx,dy);if(d<36&&dy>0){const sp=Math.max(4,Math.hypot(p.vx,p.vy));p.vx=(dx/d)*sp;p.vy=(dy/d)*sp}const ax=320+(p.x-320)*.45,ay=80;if(Math.hypot(p.x-ax,p.y-ay)<34&&p.y<150)p.vy=Math.abs(p.vy);ctx.clearRect(0,0,640,420);ctx.fillStyle='#eef7f8';ctx.fillRect(0,0,640,420);ctx.strokeStyle='#b7dce2';ctx.lineWidth=4;ctx.strokeRect(4,4,632,412);ctx.beginPath();ctx.arc(320,210,60,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,210);ctx.lineTo(640,210);ctx.stroke();ctx.fillStyle='#493e3a';ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c9858d';ctx.beginPath();ctx.arc(player.current.x,player.current.y,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#7caeb9';ctx.beginPath();ctx.arc(ax,ay,27,0,Math.PI*2);ctx.fill();id=requestAnimationFrame(loop)}loop();return()=>cancelAnimationFrame(id)},[])
 return <div><div className="arcade-score">Tú {score[0]} — {score[1]} Rival</div><canvas ref={canvas} width={640} height={420} className="arcade-canvas" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();player.current={x:Math.max(28,Math.min(612,(e.clientX-r.left)*640/r.width)),y:Math.max(240,Math.min(392,(e.clientY-r.top)*420/r.height))}}}/></div>}

export function LivePong({sessionId,userId,hostId}:{sessionId:string;userId:string;hostId:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const myY=useRef(210);const otherY=useRef(210);const ball=useRef({x:320,y:210,vx:4.2,vy:3});const [score,setScore]=useState([0,0]);const [connected,setConnected]=useState(false);const isHost=userId===hostId;const channel=useRef<any>(null)
 useEffect(()=>{const s=createClient();const ch=s.channel(`pong-${sessionId}`,{config:{broadcast:{self:false},presence:{key:userId}}});channel.current=ch;ch.on('broadcast',{event:'paddle'},({payload}:any)=>{otherY.current=payload.y}).on('broadcast',{event:'state'},({payload}:any)=>{if(!isHost){ball.current=payload.ball;setScore(payload.score)}}).on('presence',{event:'sync'},()=>setConnected(Object.values(ch.presenceState()).flat().length>1)).subscribe(async(st:any)=>{if(st==='SUBSCRIBED')await ch.track({userId})});return()=>{s.removeChannel(ch)}},[sessionId,userId,isHost])
 useEffect(()=>{let id=0,lastSend=0;const c=canvas.current!,ctx=c.getContext('2d')!;function loop(t:number){const b=ball.current;if(isHost){b.x+=b.vx;b.y+=b.vy;if(b.y<8||b.y>412)b.vy*=-1;const leftY=myY.current,rightY=otherY.current;if(b.x<34&&Math.abs(b.y-leftY)<58)b.vx=Math.abs(b.vx)*1.01;if(b.x>606&&Math.abs(b.y-rightY)<58)b.vx=-Math.abs(b.vx)*1.01;if(b.x<0){setScore(sc=>{const n=[sc[0],sc[1]+1];channel.current?.send({type:'broadcast',event:'state',payload:{ball:{x:320,y:210,vx:4.2,vy:3},score:n}});return n});Object.assign(b,{x:320,y:210,vx:4.2,vy:3})}if(b.x>640){setScore(sc=>{const n=[sc[0]+1,sc[1]];channel.current?.send({type:'broadcast',event:'state',payload:{ball:{x:320,y:210,vx:-4.2,vy:-3},score:n}});return n});Object.assign(b,{x:320,y:210,vx:-4.2,vy:-3})}if(t-lastSend>50){lastSend=t;channel.current?.send({type:'broadcast',event:'state',payload:{ball:{...b},score}})}}ctx.clearRect(0,0,640,420);ctx.fillStyle='#2c2832';ctx.fillRect(0,0,640,420);ctx.fillStyle='#fff';ctx.globalAlpha=.2;for(let yy=0;yy<420;yy+=30)ctx.fillRect(318,yy,4,17);ctx.globalAlpha=1;const left=isHost?myY.current:otherY.current,right=isHost?otherY.current:myY.current;ctx.fillRect(18,left-50,12,100);ctx.fillRect(610,right-50,12,100);ctx.beginPath();ctx.arc(b.x,b.y,9,0,Math.PI*2);ctx.fill();id=requestAnimationFrame(loop)}id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[isHost,score])
 function move(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();myY.current=Math.max(55,Math.min(365,(e.clientY-r.top)*420/r.height));channel.current?.send({type:'broadcast',event:'paddle',payload:{y:myY.current}})}
 return <div><div className="arcade-score">{connected?'🟢 Rival conectado':'⚪ Esperando rival'} · {score[0]} — {score[1]}</div><canvas ref={canvas} width={640} height={420} className="arcade-canvas" onPointerMove={move}/><p className="tiny">El creador de la partida mantiene la pelota autoritativa; la otra pantalla sincroniza paleta y marcador mediante Supabase Realtime.</p></div>
}

export function LiveAirHockey({sessionId,userId,hostId}:{sessionId:string;userId:string;hostId:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const me=useRef({x:320,y:340});const other=useRef({x:320,y:80});const puck=useRef({x:320,y:210,vx:3.1,vy:3.6});const [score,setScore]=useState([0,0]);const [connected,setConnected]=useState(false);const isHost=userId===hostId;const channel=useRef<any>(null)
 useEffect(()=>{const s=createClient();const ch=s.channel(`hockey-${sessionId}`,{config:{broadcast:{self:false},presence:{key:userId}}});channel.current=ch;ch.on('broadcast',{event:'mallet'},({payload}:any)=>{other.current=payload.pos}).on('broadcast',{event:'state'},({payload}:any)=>{if(!isHost){puck.current=payload.puck;setScore(payload.score)}}).on('presence',{event:'sync'},()=>setConnected(Object.values(ch.presenceState()).flat().length>1)).subscribe(async(st:any)=>{if(st==='SUBSCRIBED')await ch.track({userId})});return()=>{s.removeChannel(ch)}},[sessionId,userId,isHost])
 useEffect(()=>{let id=0,last=0;const c=canvas.current!,ctx=c.getContext('2d')!;function collide(p:{x:number;y:number;vx:number;vy:number},m:{x:number;y:number}){const dx=p.x-m.x,dy=p.y-m.y,d=Math.hypot(dx,dy);if(d<38&&d>0){const sp=Math.max(4.2,Math.hypot(p.vx,p.vy));p.vx=dx/d*sp;p.vy=dy/d*sp}}function loop(t:number){const p=puck.current;if(isHost){p.x+=p.vx;p.y+=p.vy;if(p.x<14||p.x>626)p.vx*=-1;collide(p,me.current);collide(p,other.current);if(p.y<0){setScore(sc=>[sc[0]+1,sc[1]]);Object.assign(p,{x:320,y:210,vx:3.1,vy:3.6})}if(p.y>420){setScore(sc=>[sc[0],sc[1]+1]);Object.assign(p,{x:320,y:210,vx:-3.1,vy:-3.6})}if(t-last>50){last=t;channel.current?.send({type:'broadcast',event:'state',payload:{puck:{...p},score}})}}ctx.clearRect(0,0,640,420);ctx.fillStyle='#edf7f8';ctx.fillRect(0,0,640,420);ctx.strokeStyle='#acd1d8';ctx.lineWidth=4;ctx.strokeRect(4,4,632,412);ctx.beginPath();ctx.moveTo(0,210);ctx.lineTo(640,210);ctx.stroke();ctx.beginPath();ctx.arc(320,210,55,0,Math.PI*2);ctx.stroke();const bottom=isHost?me.current:other.current,top=isHost?other.current:me.current;ctx.fillStyle='#b86f7b';ctx.beginPath();ctx.arc(bottom.x,bottom.y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6b91aa';ctx.beginPath();ctx.arc(top.x,top.y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#322e35';ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();id=requestAnimationFrame(loop)}id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[isHost,score])
 function move(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();const x=Math.max(28,Math.min(612,(e.clientX-r.left)*640/r.width));const raw=(e.clientY-r.top)*420/r.height;const y=isHost?Math.max(238,Math.min(392,raw)):Math.max(28,Math.min(182,raw));me.current={x,y};channel.current?.send({type:'broadcast',event:'mallet',payload:{pos:me.current}})}
 return <div><div className="arcade-score">{connected?'🟢 Rival conectado':'⚪ Esperando rival'} · {score[0]} — {score[1]}</div><canvas ref={canvas} width={640} height={420} className="arcade-canvas" onPointerMove={move}/><p className="tiny">Cada jugador controla su mitad; disco, posiciones y marcador se sincronizan por Realtime.</p></div>
}

export function LiveSnakeDuo({sessionId,userId,hostId}:{sessionId:string;userId:string;hostId:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const isHost=userId===hostId;const [connected,setConnected]=useState(false);const [score,setScore]=useState([0,0]);const channel=useRef<any>(null)
 const me=useRef({x:isHost?120:520,y:210,vx:isHost?3:-3,vy:0});const other=useRef({x:isHost?520:120,y:210,vx:isHost?-3:3,vy:0});const food=useRef({x:320,y:210});
 useEffect(()=>{const s=createClient();const ch=s.channel(`snake-${sessionId}`,{config:{broadcast:{self:false},presence:{key:userId}}});channel.current=ch;ch.on('broadcast',{event:'move'},({payload}:any)=>{other.current=payload.pos}).on('broadcast',{event:'state'},({payload}:any)=>{if(!isHost){food.current=payload.food;setScore(payload.score)}}).on('presence',{event:'sync'},()=>setConnected(Object.values(ch.presenceState()).flat().length>1)).subscribe(async(st:any)=>{if(st==='SUBSCRIBED')await ch.track({userId})});return()=>{s.removeChannel(ch)}},[sessionId,userId,isHost])
 useEffect(()=>{let raf=0,last=0;const c=canvas.current!,ctx=c.getContext('2d')!;function tick(t:number){const p=me.current;p.x=(p.x+p.vx+640)%640;p.y=(p.y+p.vy+420)%420;if(Math.hypot(p.x-food.current.x,p.y-food.current.y)<22){setScore(sc=>{const idx=isHost?0:1,n:[number,number]=[sc[0],sc[1]];n[idx]++;return n});if(isHost)food.current={x:60+Math.random()*520,y:60+Math.random()*300}}if(t-last>60){last=t;channel.current?.send({type:'broadcast',event:'move',payload:{pos:{...p}}});if(isHost)channel.current?.send({type:'broadcast',event:'state',payload:{food:food.current,score}})}ctx.clearRect(0,0,640,420);ctx.fillStyle='#15221a';ctx.fillRect(0,0,640,420);ctx.fillStyle='#f3c76a';ctx.beginPath();ctx.arc(food.current.x,food.current.y,10,0,Math.PI*2);ctx.fill();for(const [pos,color] of [[isHost?me.current:other.current,'#92d3a3'],[isHost?other.current:me.current,'#d69aa2']] as any[]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(pos.x,pos.y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.75)';ctx.beginPath();ctx.arc(pos.x+5,pos.y-4,3,0,Math.PI*2);ctx.fill()}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[isHost,score])
 function steer(dx:number,dy:number){me.current.vx=dx;me.current.vy=dy;channel.current?.send({type:'broadcast',event:'move',payload:{pos:me.current}})}
 return <div><div className="arcade-score">{connected?'🟢 Rival conectado':'⚪ Esperando rival'} · {score[0]} — {score[1]}</div><canvas ref={canvas} width={640} height={420} className="arcade-canvas"/><div className="snake-controls"><button onPointerDown={()=>steer(0,-3.4)}>↑</button><div><button onPointerDown={()=>steer(-3.4,0)}>←</button><button onPointerDown={()=>steer(3.4,0)}>→</button></div><button onPointerDown={()=>steer(0,3.4)}>↓</button></div><p className="tiny">Recojan el orbe. Cada teléfono envía solo movimiento; el host comparte objetivo y marcador.</p></div>
}

export function LiveTurboRace({sessionId,userId}:{sessionId:string;userId:string}){
 const [me,setMe]=useState(0),[other,setOther]=useState(0),[connected,setConnected]=useState(false);const [light,setLight]=useState<'ready'|'wait'|'go'>('ready');const channel=useRef<any>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null)
 useEffect(()=>{const s=createClient();const ch=s.channel(`race-${sessionId}`,{config:{broadcast:{self:false},presence:{key:userId}}});channel.current=ch;ch.on('broadcast',{event:'progress'},({payload}:any)=>setOther(payload.progress)).on('broadcast',{event:'start'},({payload}:any)=>startLocal(Number(payload.goAt))).on('presence',{event:'sync'},()=>setConnected(Object.values(ch.presenceState()).flat().length>1)).subscribe(async(st:any)=>{if(st==='SUBSCRIBED')await ch.track({userId})});return()=>{if(timer.current)clearTimeout(timer.current);s.removeChannel(ch)}},[sessionId,userId])
 function startLocal(goAt:number){setMe(0);setOther(0);setLight('wait');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setLight('go');navigator.vibrate?.(40)},Math.max(80,goAt-Date.now()))}
 function start(){const goAt=Date.now()+1500;startLocal(goAt);channel.current?.send({type:'broadcast',event:'start',payload:{goAt}})}
 function tap(){if(light==='ready')return start();if(light==='wait'){setMe(0);setLight('ready');return}setMe(v=>{const n=Math.min(100,v+4+Math.random()*3);channel.current?.send({type:'broadcast',event:'progress',payload:{progress:n}});return n})}
 const winner=me>=100?'Tú ganaste 🏁':other>=100?'Ganó tu persona 🏁':''
 return <div className="race-wrap"><div className="arcade-score">{connected?'🟢 Rival conectado':'⚪ Esperando rival'}</div><div className={`race-light ${light}`}>{light==='ready'?'Toca para iniciar':light==='wait'?'Espera la salida…':'¡ACELERA!'}</div><div className="race-track"><div className="lane"><span style={{left:`${Math.min(94,me*.94)}%`}}>🏎️</span><i/></div><div className="lane"><span style={{left:`${Math.min(94,other*.94)}%`}}>🚙</span><i/></div></div><button className="race-tap" onPointerDown={tap} disabled={!!winner}>{winner||'TOCAR / ACELERAR'}</button></div>
}
