'use client'
import React,{useEffect,useMemo,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'

type SoloDef={id:string;title:string;emoji:string;desc:string;reward:string}
type Reward={coins:number;xp:number;rewarded:boolean;daily_rewarded?:number;daily_limit?:number}
const SOLO:SoloDef[]=[
 {id:'memory',title:'Memoria',emoji:'🧠',desc:'Encuentra las parejas antes de agotar tus movimientos.',reward:'10 monedas · 15 XP'},
 {id:'2048',title:'2048',emoji:'🔢',desc:'Combina fichas y alcanza 256 o más.',reward:'12 monedas · 18 XP'},
 {id:'snake',title:'Snake clásico',emoji:'🐍',desc:'Come, crece y supera 8 puntos.',reward:'10 monedas · 15 XP'},
 {id:'trivia-solo',title:'Trivia individual',emoji:'🧩',desc:'Cinco preguntas rápidas para sumar recursos.',reward:'9 monedas · 12 XP'},
 {id:'reaction-solo',title:'Reflejos',emoji:'⚡',desc:'Tres intentos para conseguir tu mejor reacción.',reward:'6 monedas · 12 XP'},
 {id:'word-scramble',title:'Palabras revueltas',emoji:'🔤',desc:'Ordena cinco palabras antes de rendirte.',reward:'8 monedas · 12 XP'},
 {id:'tap-rush',title:'Tap Rush',emoji:'🎯',desc:'Toca el objetivo tantas veces como puedas en 10 s.',reward:'7 monedas · 12 XP'},
 {id:'block-solo',title:'Block Solo',emoji:'🧱',desc:'Completa una línea de cinco bloques.',reward:'9 monedas · 12 XP'},
]

export default function SoloGames({onReward}:{onReward?:(coins:number,xp:number)=>void}){
 const s=useMemo(()=>createClient(),[]),[game,setGame]=useState<SoloDef|null>(null),[runId,setRunId]=useState<string|null>(null),[message,setMessage]=useState(''),[reward,setReward]=useState<Reward|null>(null),[busy,setBusy]=useState(false)
 async function open(g:SoloDef){setBusy(true);setMessage('');setReward(null);const {data,error}=await s.rpc('start_solo_game',{p_game_key:g.id});setBusy(false);if(error){setMessage('No pudimos iniciar: '+error.message);return}setRunId(data?.id||null);setGame(g)}
 async function finish(score:number){if(!runId||busy)return;setBusy(true);const {data,error}=await s.rpc('finish_solo_game',{p_run_id:runId,p_score:Math.max(0,Math.floor(score))});setBusy(false);if(error){const t=(error.message||'').toUpperCase();setMessage(t.includes('PLAY_A_LITTLE_LONGER')?'Juega unos segundos más antes de cerrar la ronda.':'No pudimos guardar la recompensa: '+error.message);return}const r=data as Reward;setReward(r);onReward?.(Number(r.coins||0),Number(r.xp||0))}
 function close(){setGame(null);setRunId(null);setReward(null);setMessage('')}
 if(game&&runId)return <div className="solo-room"><button className="game-back" onClick={close}>← Juegos individuales</button><div className="solo-room-head"><span>{game.emoji}</span><div><div className="eyebrow">Jugar solo</div><h2>{game.title}</h2></div></div>{message&&<div className="notice">{message}</div>}{reward?<RewardCard reward={reward} onAgain={()=>open(game)} onBack={close}/>:<SoloEngine id={game.id} busy={busy} onFinish={finish}/>}</div>
 return <section className="solo-section"><div className="solo-banner"><div><span className="tag">🎮 Sin esperar a nadie</span><h2>Jugar solo</h2><p>Termina una partida y gana monedas + XP para la mascota. Las primeras 12 recompensas del día dan monedas; un mismo juego paga monedas hasta 3 veces al día.</p></div><div className="solo-wallet-hint">🐾 Recursos para Nuestro mundo</div></div>{message&&<div className="notice">{message}</div>}<div className="game-grid">{SOLO.map(g=><button disabled={busy} key={g.id} className="game-card solo-card" onClick={()=>open(g)}><div className="game-icon">{g.emoji}</div><div><span className="mode-pill solo">INDIVIDUAL</span><h3>{g.title}</h3><p>{g.desc}</p><small>{g.reward}</small></div><b>→</b></button>)}</div></section>
}
function RewardCard({reward,onAgain,onBack}:{reward:Reward;onAgain:()=>void;onBack:()=>void}){return <div className="solo-reward"><div className="reveal-burst">✨</div><h2>{reward.rewarded?'¡Recompensa conseguida!':'Ronda completada'}</h2><div className="reward-pills"><span>🪙 +{reward.coins}</span><span>⭐ +{reward.xp} XP</span></div>{!reward.rewarded&&<p>Esta ronda ya no da monedas por el límite anti-farmeo, pero todavía suma un poco de XP y puntos.</p>}{reward.daily_limit&&<p className="tiny">Recompensas con monedas hoy: {reward.daily_rewarded}/{reward.daily_limit}</p>}<div className="actions"><button className="btn" onClick={onAgain}>Jugar otra vez</button><button className="btn ghost" onClick={onBack}>Elegir otro</button></div></div>}
function SoloEngine({id,onFinish,busy}:{id:string;onFinish:(score:number)=>void;busy:boolean}){if(id==='memory')return <Memory onFinish={onFinish} busy={busy}/>;if(id==='2048')return <Game2048 onFinish={onFinish} busy={busy}/>;if(id==='snake')return <Snake onFinish={onFinish} busy={busy}/>;if(id==='trivia-solo')return <Trivia onFinish={onFinish} busy={busy}/>;if(id==='reaction-solo')return <Reaction onFinish={onFinish} busy={busy}/>;if(id==='word-scramble')return <Words onFinish={onFinish} busy={busy}/>;if(id==='tap-rush')return <TapRush onFinish={onFinish} busy={busy}/>;return <BlockSolo onFinish={onFinish} busy={busy}/>}

function Memory({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const icons=['🌙','🌿','⭐','🐾','🍓','🎈'],[cards]=useState(()=>[...icons,...icons].map((v,i)=>({v,k:i})).sort(()=>Math.random()-.5)),[open,setOpen]=useState<number[]>([]),[done,setDone]=useState<number[]>([]),[moves,setMoves]=useState(0);function pick(i:number){if(open.length===2||open.includes(i)||done.includes(i))return;const n=[...open,i];setOpen(n);if(n.length===2){setMoves(m=>m+1);setTimeout(()=>{if(cards[n[0]].v===cards[n[1]].v)setDone(d=>[...d,...n]);setOpen([])},500)}}const won=done.length===cards.length;return <div className="solo-game-card"><div className="solo-stats"><b>Movimientos: {moves}</b><span>Parejas: {done.length/2}/6</span></div><div className="memory-grid">{cards.map((c,i)=><button key={c.k} className={open.includes(i)||done.includes(i)?'open':''} onClick={()=>pick(i)}>{open.includes(i)||done.includes(i)?c.v:'?'}</button>)}</div>{won&&<button disabled={busy} className="btn" onClick={()=>onFinish(Math.max(10,120-moves*5))}>Cobrar recompensa</button>}</div>}

function emptyBoard(){const b=Array(16).fill(0);b[Math.floor(Math.random()*16)]=2;b[Math.floor(Math.random()*16)]=2;return b}
function Game2048({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [b,setB]=useState<number[]>(emptyBoard),[moves,setMoves]=useState(0);function move(dir:'l'|'r'|'u'|'d'){let a=[...b],changed=false;const lines:number[][]=[];for(let i=0;i<4;i++)lines.push(dir==='l'||dir==='r'?[0,1,2,3].map(x=>i*4+x):[0,1,2,3].map(x=>x*4+i));for(const raw of lines){const idx=dir==='r'||dir==='d'?[...raw].reverse():raw;const vals=idx.map(i=>a[i]).filter(Boolean);const out:number[]=[];for(let j=0;j<vals.length;j++){if(vals[j]===vals[j+1]){out.push(vals[j]*2);j++}else out.push(vals[j])}while(out.length<4)out.push(0);idx.forEach((k,j)=>{if(a[k]!==out[j])changed=true;a[k]=out[j]})}if(changed){const empt=a.map((v,i)=>v?null:i).filter(v=>v!==null) as number[];if(empt.length)a[empt[Math.floor(Math.random()*empt.length)]]=Math.random()<.9?2:4;setB(a);setMoves(m=>m+1)}}const max=Math.max(...b);return <div className="solo-game-card"><div className="solo-stats"><b>Máximo: {max}</b><span>Movimientos: {moves}</span></div><div className="g2048">{b.map((v,i)=><div key={i} data-v={v}>{v||''}</div>)}</div><div className="dpad"><button onClick={()=>move('u')}>↑</button><div><button onClick={()=>move('l')}>←</button><button onClick={()=>move('d')}>↓</button><button onClick={()=>move('r')}>→</button></div></div><button disabled={busy||max<128} className="btn" onClick={()=>onFinish(max+moves)}>Terminar y cobrar {max<128?'(llega a 128)':''}</button></div>}

function Snake({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [snake,setSnake]=useState([[5,5]]),[food,setFood]=useState([2,2]),[dir,setDir]=useState([1,0]),[running,setRunning]=useState(false),[over,setOver]=useState(false);useEffect(()=>{if(!running)return;const t=setInterval(()=>setSnake(old=>{const h=[old[0][0]+dir[0],old[0][1]+dir[1]];if(h[0]<0||h[0]>=12||h[1]<0||h[1]>=12||old.some(p=>p[0]===h[0]&&p[1]===h[1])){setOver(true);setRunning(false);return old}const ate=h[0]===food[0]&&h[1]===food[1];if(ate)setFood([Math.floor(Math.random()*12),Math.floor(Math.random()*12)]);return [h,...old.slice(0,ate?old.length:old.length-1)]}),170);return()=>clearInterval(t)},[running,dir,food]);function d(x:number,y:number){if(dir[0]!==-x||dir[1]!==-y)setDir([x,y]);setRunning(true)}const score=snake.length-1;return <div className="solo-game-card"><div className="solo-stats"><b>Puntos: {score}</b><span>Meta: 8</span></div><div className="snake-board">{Array.from({length:144},(_,i)=>{const x=i%12,y=Math.floor(i/12),isS=snake.some(p=>p[0]===x&&p[1]===y),isF=food[0]===x&&food[1]===y;return <i key={i} className={isS?'snake':isF?'food':''}/>})}</div><div className="dpad"><button onClick={()=>d(0,-1)}>↑</button><div><button onClick={()=>d(-1,0)}>←</button><button onClick={()=>d(0,1)}>↓</button><button onClick={()=>d(1,0)}>→</button></div></div>{(over||score>=8)&&<button disabled={busy||score<4} className="btn" onClick={()=>onFinish(score*10)}>Terminar {score<4?'(consigue 4 puntos)':''}</button>}</div>}

const QS=[['¿Cuál es el planeta más grande?',['Marte','Júpiter','Venus'],1],['¿Cuántos lados tiene un hexágono?',['5','6','8'],1],['¿Qué océano es el más grande?',['Pacífico','Atlántico','Índico'],0],['¿Qué animal es mamífero?',['Tiburón','Delfín','Pulpo'],1],['¿Cuánto es 9 × 7?',['56','63','72'],1]] as const
function Trivia({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [i,setI]=useState(0),[ok,setOk]=useState(0),[answered,setAnswered]=useState(false);function a(n:number){if(answered)return;setAnswered(true);if(n===QS[i][2])setOk(x=>x+1);setTimeout(()=>{setAnswered(false);setI(x=>x+1)},450)}if(i>=QS.length)return <div className="solo-game-card center"><div className="reveal-burst">🧠</div><h2>{ok}/5 correctas</h2><button disabled={busy} className="btn" onClick={()=>onFinish(ok*20)}>Cobrar recompensa</button></div>;return <div className="solo-game-card"><div className="solo-stats"><b>Pregunta {i+1}/5</b><span>Aciertos: {ok}</span></div><h3>{QS[i][0]}</h3><div className="solo-options">{QS[i][1].map((x,n)=><button disabled={answered} onClick={()=>a(n)} key={x}>{x}</button>)}</div></div>}

function Reaction({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [round,setRound]=useState(0),[state,setState]=useState<'idle'|'wait'|'go'>('idle'),[times,setTimes]=useState<number[]>([]),start=useRef(0),timer=useRef<any>(null);function begin(){setState('wait');timer.current=setTimeout(()=>{start.current=performance.now();setState('go')},900+Math.random()*1800)}function tap(){if(state==='wait'){clearTimeout(timer.current);setState('idle');return}if(state!=='go')return;const ms=Math.round(performance.now()-start.current);setTimes(t=>[...t,ms]);setRound(r=>r+1);setState('idle')}const complete=round>=3,best=times.length?Math.min(...times):0;return <div className="solo-game-card center"><div className="solo-stats"><b>Intento {Math.min(3,round+1)}/3</b><span>Mejor: {best||'—'} ms</span></div>{!complete?<button className={`reaction-pad ${state}`} onClick={state==='idle'?begin:tap}>{state==='idle'?'Preparar':state==='wait'?'Espera…':'¡TOCA!'}</button>:<><div className="reveal-burst">⚡</div><h2>{best} ms</h2><button disabled={busy} className="btn" onClick={()=>onFinish(Math.max(1,1000-best))}>Cobrar recompensa</button></>}</div>}

const WORDS=['MASCOTA','AVENTURA','ESTRELLA','PAREJA','JARDIN']
function Words({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [i,setI]=useState(0),[text,setText]=useState(''),[ok,setOk]=useState(0);const word=WORDS[i]||'',scramble=useMemo(()=>word.split('').sort(()=>Math.random()-.5).join(''),[word]);function send(){if(text.trim().toUpperCase()===word)setOk(x=>x+1);setText('');setI(x=>x+1)}if(i>=WORDS.length)return <div className="solo-game-card center"><div className="reveal-burst">🔤</div><h2>{ok}/5 palabras</h2><button disabled={busy} className="btn" onClick={()=>onFinish(ok*20)}>Cobrar recompensa</button></div>;return <div className="solo-game-card center"><div className="solo-stats"><b>Palabra {i+1}/5</b><span>Aciertos: {ok}</span></div><div className="scramble">{scramble}</div><input className="game-input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Escribe la palabra"/><button className="btn" onClick={send}>Comprobar</button></div>}

function TapRush({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [sec,setSec]=useState(10),[hits,setHits]=useState(0),[running,setRunning]=useState(false),[pos,setPos]=useState([50,50]);useEffect(()=>{if(!running)return;const t=setInterval(()=>setSec(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[running]);function hit(){if(!running){setRunning(true)}setHits(h=>h+1);setPos([10+Math.random()*80,10+Math.random()*75])}return <div className="solo-game-card"><div className="solo-stats"><b>{sec}s</b><span>Toques: {hits}</span></div><div className="tap-arena">{sec>0?<button style={{left:`${pos[0]}%`,top:`${pos[1]}%`}} onClick={hit}>🎯</button>:<div className="tap-end">¡Tiempo!</div>}</div>{sec===0&&<button disabled={busy} className="btn" onClick={()=>onFinish(hits*10)}>Cobrar recompensa</button>}</div>}

function BlockSolo({onFinish,busy}:{onFinish:(n:number)=>void;busy:boolean}){const [filled,setFilled]=useState<Set<number>>(new Set),[moves,setMoves]=useState(0);function place(i:number){setFilled(old=>{const n=new Set(old);n.add(i);return n});setMoves(m=>m+1)}const lines=[0,1,2,3,4].filter(r=>[0,1,2,3,4].every(c=>filled.has(r*5+c))).length;return <div className="solo-game-card"><div className="solo-stats"><b>Líneas: {lines}</b><span>Bloques: {moves}</span></div><div className="block-grid">{Array.from({length:25},(_,i)=><button key={i} disabled={filled.has(i)} className={filled.has(i)?'filled':''} onClick={()=>place(i)}/>)}</div>{lines>0&&<button disabled={busy} className="btn" onClick={()=>onFinish(lines*50+Math.max(0,50-moves))}>Cobrar recompensa</button>}</div>}
